### ISSUE TITLE
Mythos - Your Darkest Secrets softlocks if a hero's hand changes in the middle

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#1002]
**Describe the bug**
If, in the middle of a hero taking damage from Your Darkest Secrets, something causes their hand to change (Gritty Reboot draws, Vanish discarding to activate Jaunting Reflex, YDS doing enough damage to incapacitate...) the game softlocks.

**What does it affect**
Card(s): Your Darkest Secrets
Deck(s): Mythos

**To Reproduce**
1. Play Quicksilver vs. Mythos
2. Get out an Iron Retort. Don't use it until...
3. Get Mythos to play Your Darkest Secrets. Have Quicksilver play off of Iron Retort when she takes damage from it.
4. Wee the game freeze.

**Expected behavior**
Your Darkest Secrets should not crash.

**Comment by wrhyme29** [comment]
Closed by #1004
