### ISSUE TITLE
Phrasing Fix: Need A Way Out (Echelon)

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1031]
Start of turn: "Do you want to use a power twice?"

Actual effect: allows the hero to use two different powers.

**Comment by wrhyme29** [comment]
This is an engine limitation, as we do not have control over the text for these UI decisions. 

Are options at this point are:
1) Do you want to use a power twice now?
2) Do you want to use a power again now?
3) Do you want to use a power now?

Of which, none fit super well. Leaving this open for when Handelabra gives us the ability to have custom text for decisions
