### ISSUE TITLE
Catchwater Harbor 1929: Left Behind breaks when there are no heroes in its battle zone

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1040]
**Describe the bug**
If Left Behind is played in a battle zone with no heroes, I think it gets put back on top of the environment deck somehow. It didn't go into the trash, and it got played again the next turn, so I'm assuming that's what happened.

**What does it affect**
Card(s): Left Behind
Deck(s): Catchwater Harbor 1929

**To Reproduce**
1. Play in OblivAeon mode in Catchwater Harbor 1929
2. Have no heroes in the battle zone with Catchwater Harbor 1929
3. Play Left Behind from the environment deck

**Expected behavior**
Given the behavior of cards like Shinobi Assassin when there are no heroes in the battle zone, it should probably just go to the environment trash

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by wrhyme29** [comment]
I think this will likely apply to any environment card that goes next to hero character cards not just Left Behind. I'll have to go through and find all instances like this across decks
