### ISSUE TITLE
Could not start Multiplayer Oblivaeon with a Cauldron hero in first position

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1051]
^as above.

**Comment by mredgecase** [comment]
Was able to start two multiplayer OA games today - maybe fixed by the new Handelabra release?

**Comment by wrhyme29** [comment]
Do you know if either times the hero in the first position was a variant? There may be a difference from between variants and base heroes.

Additionally, I'm curious if you put Area 51 Starlight in the first position, are you still able to load without issue, as she was the hero in the first position the first time around.

**Comment by mredgecase** [comment]
Was just able to start a multiplayer OA with A51 Starlight in 1st position
