### ISSUE TITLE
Impact: Crushing Rift automatically goes after ... something, somehow

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1067]
**Describe the bug**
With the only eligible targets for Crushing Rift being Cold War (at 14HP) and Chronoist (just flipped, also at 14 HP), Impact plays Crushing Rift during his End of Turn phase, permitted to do so because of Chronoist. 

Crushing Rift halves Cold War to 7 HP. No prompt to select Chronoist appears. 

**What does it affect**
Card(s): Crushing Rift
Deck(s): Impact

**Expected behavior**
Prompt asking me to choose between Cold War and Chronoist.

**Comment by LNBertolini** [comment]
This is expected - Chronoist, having just flipped, is still at max HP and therefore not a valid target for Crushing Rift.
