### ISSUE TITLE
Titan - Can use innate power twice in a turn if Titanform enters/leaves play

### ISSUE THREAD

**Issue by bobbertoriley** [SotMSteamMods/CauldronMods#1074]
**Describe the bug**
If Titan gets Titanform into play after using his innate power, he can use it again.

**What does it affect**
Card(s): Titan's character cards
Deck(s): Titan

**To Reproduce**
1. Grant Titan a Power. Use his innate power.
2. Grant Titan a Play. Play a card that results with Titanform in play (if Titanform is already in play, instead play a card that destroys Titanform).
3. Grant Titan a Power. Use his innate power.

**Expected behavior**
Titan should not be able to use his character card's innate power, as it's already been used this turn.

**Additional context**
The easiest way I've found to consistently reproduce is get Argent Adept setup and give him multiple ways to execute powers, Lyra + Polyphoric Flare 

This will likely also impact Drift if she swaps between Red/Blue state, since both are represented by different character cards.

**Comment by wrhyme29** [comment]
I did some research here and couldn't find a good way to manually adjust the number of uses. Can continue to look into this later.

Test case for future use:

` [Test()]
        public void TestTitanMultiplePowerUseThroughFormChange()
        {
            SetupGameController("Omnitron", "TheArgentAdept", "Cauldron.Titan", "TheScholar", "VoidGuardDrMedico", "Megalopolis");
            StartGame();

            PlayCard("InspiringSupertonic");
            AssertNextDecisionChoices(included: titan.TurnTaker.ToEnumerable());
            UsePower(adept);
            PlayCard("Titanform");
            AssertNextDecisionChoices(notIncluded: titan.TurnTaker.ToEnumerable());
            UsePower(adept);
        }`
