### ISSUE TITLE
Irradiated cards can't be dragged into play.

### ISSUE THREAD

**Issue by Snaid1** [SotMSteamMods/CauldronMods#1083]
Apologies if this bug exists, I couldn't find it listed anywhere.

**Describe the bug**
When a card  in your hand is marked Irradiated (has an irradiated card beside/behind it). I cannot drag the card into the play area to play it. In order to play it I have to double click the card and then click "Play Card"

**What does it affect**
Card(s): Any card that has been "irradiated"
Deck(s): Pyro

**To Reproduce**
1. Use this setup
  Any hero team including Pyro
2. Play these cards to setup
  Any card or power of Pryo's that cause it to make cards in hand irradiated.
3. Play the problem card
  attempt to play irradiated card by dragging it into the play area during the play phase.

**Expected behavior**
When I drag a card from my hand to the play area during the play phase, it should be played whether the card is irradiated or not. (not irradiated works)

**Logs**
no freezing or soft locks. can still provide a log if you think it would help.

**Comment by wrhyme29** [comment]
This is a known issue that was announced in the release that introduces Pyre. It is a limitation of this implementation of Pyre that we have decided is adequate for now.
