### ISSUE TITLE
Pirate Gyrosaur Resolving Cards

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#1092]
**Describe the bug**
When Captain Gyrosaur resolves cards beneath her, I don't believe the cards finish resolving before it moves on - Ricochet didn't do it's second instant of damage before the next card, Terrifying Momentum, got put into play. 

**What does it affect**
Card(s): Ricochet
Deck(s): Gyrosaur

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by LNBertolini** [comment]
This is intended - it's *whenever* Gyrosaur deals damage, and Ricochet deals damage, so Terrifying Momentum goes "aha, damage was dealt, time to come out to play!"
