### ISSUE TITLE
Nightlore Armor requires more than one Constellation to blow up if option to redirect exists

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1117]
**Describe the bug**
When the player is presented with "which should take effect first", when Nightlore Armor and Lead From The Front are in play, the following occurs if Nightlore Armor activates first: 
- Destroy a constellation to block the damage: yes. Expectation is that this blocks the damage. However: the user is prompted a second time.  
- Destroy a constellation to block the damage (the second time): if the user picks yes, a total of two constellations are destroyed and the damage is blocked. 
- If the user clicks 'no' the second time they are prompted, a constellation ends up having been destroyed to no effect; the damage goes through. 

If Lead from the Front is chosen to activate first, then declined, Nightlore Armor acts correctly - only one constellation needs to be destroyed to block the damage. 

**What does it affect**
Card(s): Nightlore Armor; (Lead From The Front; presumably also Coup Vexant; 
Deck(s): Starlight

**To Reproduce**
1. Use this setup: Starlight with constellations on other heroes and Nightlore Armor in play; Legacy with Lead from the Front in play. 
2. Villain initiates damage to a non-Starlight character. 
3. Observe prompts. 

**Expected behavior**
Destroying a single constellation blocks damage, regardless of if redirection is in play and not yet chosen.  

**Logs**
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6186629/output_log.txt)

**Additional context**

> From the discord: 
> 
> Lead from the Front - no  
> Nightlore armor - yes. 
> Blows up one constellation - damage is prevented. 
> 
> Nightlore Armor - yes. 
> Prevent damage - yes. 
> Destroy a constellation - yes. 
> and then I get the Nightlore armor prompt again. Prevent damage - no. and it goes through.
> 
> So yeah, it looks like an order of operations thing, where if you destroy a constellation to block it, Lead from the Front still sees it and prompts a second activation of nightlore armor.
>

**Comment by wrhyme29** [comment]
I think this is a related issue to #1066 as its prevention effects being overriden by redirection
