### ISSUE TITLE
Tiamat 2199 requires majority players to agree on draw vs play/power in multiplayer

### ISSUE THREAD

**Issue by bobbertoriley** [SotMSteamMods/CauldronMods#1126]
**Describe the bug**
After choosing which player should draw a card or play a card/use a power on the destruction clause of Neoscale/Exoscale, the player selected requires the other players to agree with them that they should play/power versus draw. This slows down the game, but also means that a player can get outvoted after being selected to perform the action.

**What does it affect**
Card(s): Neoscale and Exoscale
Deck(s): Tiamat (2199 variant)

**To Reproduce**
1. Play in a multiplayer game of Tiamat 2199.
2. Destroy Exoscale or Neoscale.
3. Select a player to perform an action (draw or play, draw or power)
4. Have just the selected player select between draw, play/power, or skip

**Expected behavior**
The player's decision should be accepted, whatever they choose.

**Comment by wrhyme29** [comment]
This doesn't seem to be something we can change. The code is just using

`SelectAndPerformFunction(this.DecisionMaker, functions, true, associatedCards: new[] { Card });`

Digging into the DLL code, it seems like it detects that it is in a Multiplayer game and uses that behavior. For yes no decisions, I know we can be explicit about it, but it doesn't look like we can in this place. 

I'm closing this issue for now, but if someone comes up with a good way to change it, I'm all for it
