### ISSUE TITLE
Missing art

### ISSUE THREAD

**Issue by drdarkwolf** [SotMSteamMods/CauldronMods#1130]
I notice some art on some locations in the preview is missing when you zoom in. For example oblask crate and dungeons of terror(All deck) there is no art on zoom pictures only base mod  art. Instalation was true workshop.2 cards in st.simeon catacoms 
![20210327215346_1](https://user-images.githubusercontent.com/71904545/112731230-0d171a80-8f47-11eb-82ac-e1f8a37d1fd6.jpg)
![20210327215349_1](https://user-images.githubusercontent.com/71904545/112731234-0e484780-8f47-11eb-8c55-5659447b68e2.jpg)
![20210327215111_1](https://user-images.githubusercontent.com/71904545/112731235-0ee0de00-8f47-11eb-9192-a90c62a22a63.jpg)
![20210327215114_1](https://user-images.githubusercontent.com/71904545/112731237-0f797480-8f47-11eb-9295-5c62d7e4dfaf.jpg)
![20210327215322_1](https://user-images.githubusercontent.com/71904545/112731240-10120b00-8f47-11eb-9f6d-c468b012592f.jpg)
![20210327215328_1](https://user-images.githubusercontent.com/71904545/112731241-10aaa180-8f47-11eb-8a1f-360c3aa3999c.jpg)

**Comment by wrhyme29** [comment]
This just required updating the art in the Workshop. It has now been updated.
