### ISSUE TITLE
Fading Realities - not so faded

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#1137]
**Describe the bug**
Cards removed from Faded Realities didn't end up removed from game.

**What does it affect**
Card(s): Faded Realities, All In, Ace of Sinners
Deck(s): Mistress of Fate, Baccarat

**To Reproduce**
1. Have Mistress of Fate Fade Realities on Baccarat, and he discards an All In and destroys an Ace of Sinners to remove both from the game. 
2. Eventually get Baccarat knocked out, and revive him.
3. Count the total number of cards available to Baccarat.

**Expected behavior**
The removed cards to stay out of the game.

**Screenshots**

**Logs**
https://pastebin.com/UjSDk19g

**Additional context**
I don't know if the card was ever actually removed properly, I only noticed the discrepancy further into the game when I ended up drawing his second Ace of Sinners while the other one was in play, then counted the amount of cards he had in his trash, deck, and hand.

**Comment by wrhyme29** [comment]
Based on the discussion in discord, this seems to be the correct behavior, so I am closing the issue
