### ISSUE TITLE
Another yes and no 

### ISSUE THREAD

**Issue by drdarkwolf** [SotMSteamMods/CauldronMods#1153]
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6222098/log.txt)
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6222099/output_log.txt)

![20210329162349_1](https://user-images.githubusercontent.com/71904545/112846271-88471080-90ae-11eb-9047-f532dc1964f6.jpg)
![20210329162447_1](https://user-images.githubusercontent.com/71904545/112846272-89783d80-90ae-11eb-8eab-2535ba5bcee2.jpg)

**Comment by wrhyme29** [comment]
Existing pull requests already fix both of these issues, closing.
