### ISSUE TITLE
yes and no with impact

### ISSUE THREAD

**Issue by drdarkwolf** [SotMSteamMods/CauldronMods#1159]
![20210330125827_1](https://user-images.githubusercontent.com/71904545/112972542-0829b500-9159-11eb-8b00-fa4d7107f90e.jpg)
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6228201/log.txt)
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6228202/output_log.txt)

**Comment by wrhyme29** [comment]
Already fixed in another PR. Closing.
