### ISSUE TITLE
MiniHP is 99 for The Knights: Wasteland Ronin

### ISSUE THREAD

**Issue by wac** [SotMSteamMods/CauldronMods#1201]
The HP in the bottom right of the mini summary card on the playing field for the Wasteland Ronin is "99" (the indicator next to "Magnifient Mara").  You can still look at their character cards which show their HP properly though.
![image](https://user-images.githubusercontent.com/28958/114316818-dacef680-9aca-11eb-924b-c9dc4b9d2f91.png)

**Comment by wrhyme29** [comment]
This is a limitation of the system currently - the Sentinels are hard coded to allow for the multiple HP boxes, and we can't take advantage of that. Hopefully Handelabra puts some changes in place in the future to allow for this to become possible on our ends
