### ISSUE TITLE
Titan's Unbreakable caused the game to get stuck

### ISSUE THREAD

**Issue by wac** [SotMSteamMods/CauldronMods#1224]
**Describe the bug**
Playing Unbreakable on Titan's turn causes the game to get stuck (maybe it's a softlock?) - music is playing,  board is interactable but it doesn't end his turn.  There isn't a prompt in Titan's play area (there is nothing where usually it will prompt to play a card or use a power),  although playing Unbreakable I expected that it pretty much means that Titan's turn should be over (no more card plays and he can no longer use powers or draw cards).

It's a regular game against regular Outlander.  It was near the end of the game so all of Outlander's traces are out - there are quite a few End of Villain turn effects in play.  Heroic Interception is also active so Outlander was reacting but also having most of the damage negated.  

**What does it affect**
Card(s):  Unbreakable
Deck(s):  Titan

**To Reproduce**
Log attached

**Expected behavior**
Titan's turn should have ended.  Previously thought there was another hero after but actually Titan was the last hero so it would be the environment next. Usually it would pop up messages indicating Titan can't use powers, draw cards (or Unbreakable prevents Titan from using powers,  Unbreakable prevents Titan from drawing cards)

Just my second time playing Outlander,  so not entirely sure (and there's a lot of stuff out of course) but I think the next expected message would be Payback Time causing Titan to try to gain 1 HP which is reduced to nothing because of Outlander's Out of Touch,  and then flipping to the Environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/28958/114806104-c9574a00-9d69-11eb-8c7c-960eb2da85c5.png)

**Additional context**
[
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6314839/log.txt)
](url)

**Comment by LNBertolini** [comment]
log.txt isn't particularly helpful here, we'd want output_log.txt since that would have the details about whatever error happened.

**Comment by wac** [comment]
Unfortunately I'd reopened Sentinels to look through Outlander's deck,  so I don't have the output_log.txt from that session anymore.  If it is helpful, I was able to rewind and play Unbreakable again to the same effect but it seemed to be waiting for something else to happen afterwards - I eventually rewound and played Forbidden Archives, and was able to finish the game from there.  If I reproduce it I'll include a output_log here.

**Comment by wac** [comment]
Reproduced!  

Legacy,  Wraith,  Titan vs Outlander in the Nightlore Citadel.
Put Titan in last place,  restarted the game till he started with Unbreakable in hand.  Played it first round (Legacy played Take Down,  Wraith used Impromptu Invention to put out Micro-Targeting and Razor Ordnance)


![image](https://user-images.githubusercontent.com/28958/114936123-a24c5700-9e01-11eb-8f77-bf4f1b941a86.png)


The output_log is complaining about the following

> MissingMethodException: Method not found: 'Handelabra.Sentinels.Engine.Controller.GameController.AddTemporaryTriggerInhibitor'.
>   at Handelabra.Sentinels.Engine.Controller.CardController.AddCardTriggers () [0x00000] in <filename unknown>:0 
>   at Handelabra.Sentinels.Engine.Controller.PlayCardAction+<DoActionOnSuccess>d__61.MoveNext () [0x00000] in <filename unknown>:0 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
>  
> (Filename:  Line: -1)
> 
> 

[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6321021/output_log.txt)
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6321037/log.txt)

**Comment by LNBertolini** [comment]
Looks like the recent SotM update changed just enough about the AddTemporaryTriggerInhibitor function to make the compiled DLLs incompatible. Doesn't need any code changes, just a new release.

**Comment by wrhyme29** [comment]
Since there was a new release, this should be resolved now. Let us know if you see this again - in the mean time, I will be closing this issue
