### ISSUE TITLE
Gyrosaur:  Wording for Gyro Stabilizer

### ISSUE THREAD

**Issue by wac** [SotMSteamMods/CauldronMods#1234]
**Describe the bug**
Currently the prompt is "What would you like to do with Gyro Stabilizer" where what it is actually letting you adjust the number of cards in hand when evaluating how many crash cards are in hand.   

It would be more helpful for the prompt to be something like "how many crash cards should be counted by Gyro Stabilizer?" .  

It would also be more useful to show the card evaluating the check rather than Gyro Stabilizer since that's likely where the interesting thresholds are mentioned.

**What does it affect**
Card(s):  Gyro Stabilizer,  Gyrosaur cards that evaluate number of crash cards in hand
Deck(s): Gyrosaur

**Screenshots**
![image](https://user-images.githubusercontent.com/28958/115120342-97650400-9f72-11eb-922b-3b8826a3bf20.png)

**Comment by wrhyme29** [comment]
Working on adjusting the decision text to be better, but I do want to note that it is showing you  what card is being evaluated on the left hand side already

**Comment by wac** [comment]
Whoops - that makes sense!
