### ISSUE TITLE
Damage dealing soft lock when trying to increase an instance of damage (Break Through, Nobility of Dusk)

### ISSUE THREAD

**Issue by wac** [SotMSteamMods/CauldronMods#1243]
**Describe the bug**
Echelon has Break Through in play.
Soft lock using Crown of Four Winds against Scream Machine - I selected a target and then game did not proceed.  
The damage preview for Crown of Four Winds was "We're working on this one" even though none of the Seasons were in play so it should be relatively straightforward. Similarly get the same preview message if I try Lady's base power after I select the damage type, so it might be the prompt for break through that is causing the crash/any damage dealing power causes this.  I was able to damage Scream Machine on previous turns.
Trying to hit Echelon also caused the lock so it does not appear to be Scream Machine in particular.
Locked also when Luminary played a drone that did damage and when the Knight tried to deal damage after playing an equipment on the young knight.
After Break Through was destroyed,  Echelon was able to deal damage without locking.

Similarly, Lady of the Wood put nobility of dusk in play and got locked trying to deal damage.

**What does it affect**
Card(s): Break Through, Nobility of Dusk (and other optional damage increases?)
Deck(s): Echelon, Lady of the Wood (maybe also Gargoyle?)

**Expected behavior**
Expected a prompt whether to increase the damage due to Echelon's Break Through?

**Screenshots**

**Logs**
Break Through
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6339165/log.txt)
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6339166/output_log.txt)

Nobility of Dusk
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6339333/log.txt)
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6339334/output_log.txt)

**Additional context**
output_log.txt complains about stuff in Handelabra's side so it might today's update.

**Comment by wrhyme29** [comment]
I believe this was because of the Handelabra stuff. Can you try to recreate this on the latest release? If you can, we will look into it

**Comment by wac** [comment]
Confirmed,  no longer an issue after the update - prompt for Break Through appeared correctly.
