### ISSUE TITLE
Residual Malus isn't dealing damage 

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#1256]
**Describe the bug**
RM isn't dealing damage upon a card being played, regardless of the number of cards in the Environment trash.

**What does it affect**
Card(s): RM
Deck(s): MoF

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**
Residual Malus to deal damage.

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by wrhyme29** [comment]
I was not able to replicate this - again I would ask, is your version v0.4.4?

**Comment by TheRealTails** [comment]
Yeah, I apparently needed to restart the game after I updated it, and both of the most recent issues I posted are due to that. I apologize for the inconvenience.
