### ISSUE TITLE
Quicksilver Liquid Metal Fizzled

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#1257]
**Describe the bug**
Quicksilver played it by Redshift, but when she went to deal herself damage to play a combo, nothing happened.

**What does it affect**
Card(s): Liquid Metal, Redshift maybe?
Deck(s): Quicksilver, Starlight maybe

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**
To be able to use the full extent of the card.

**Screenshots**

**Logs**
Redshift plays Liquid Metal.
Revealed matching card: Guard Breaker
Liquid Metal moved Guard Breaker from Quicksilver's revealed cards to Quicksilver's hand.
Liquid Metal moves 0 cards to the top of Quicksilver's Deck.
Revealed matching card: Whispering Steel
Liquid Metal moved Whispering Steel from Quicksilver's revealed cards to Quicksilver's hand.
Liquid Metal moves 0 cards to the top of Quicksilver's Deck.
Quicksilver shuffles their Quicksilver's deck.
Created decision [YesNoCard/None D79 Quicksilver]
GameController moved Liquid Metal to Quicksilver's trash.
Created decision [SelectTurnTaker/None D80 Starlight]

**Additional context**

**Comment by TheRealTails** [comment]
Quicksilver just can't deal herself any damage this game, and I don't know why. Even playing a combo regularly won't do anything.

**Comment by wrhyme29** [comment]
Can you confirm that you were on release v4.4 when this occurred?

**Comment by TheRealTails** [comment]
See other response, I suppose. :)
