### ISSUE TITLE
Acoustic Distortion should show the damage action that it’s redirecting.

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1280]
**Describe the bug**
Acoustic Distortion should show the damage action that it’s redirecting.

**What does it affect**
Card(s):Acoustic Distortion 
Deck(s):Cricket

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card
Have Acoustic Distortion  in play and have damage dealt to a hero target.

**Expected behavior**
The redirection decision should show the associated DealDamageAction.

See #1272 for attachments.

**Comment by wrhyme29** [comment]
I think this is on your end? We're using the `GameController.SelectTargetAndRedirectDamage` helper, and we are passing in the damage action. I'm not seeing any other ways to specify the damage action. Happy to look into it if you think otherwise

**Comment by MigrantP** [comment]
Hmm ok, Wrest the Mind does basically the same thing so I'll see if something broke there.

**Comment by MigrantP** [comment]
It seems fine to me so there must have been a specific situation where it didn't work in the UI, and I don't remember what it was. Wouldn't be your bug in any case, so I'll close this!
