### ISSUE TITLE
Asked about HP ordering with Snowshade Gown in play and Lady at max HP

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1284]
**Describe the bug**
Snowshade Gown’s trigger should not be applicable if she’s at full HP, otherwise it causes ordering decisions to be asked about gaining HP when she’s at full.

**What does it affect**
Card(s):Snowshade Gown
Deck(s):Lady of the Wood

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

Have Snowshade Gown in play with Lady at full HP, and do something to make all heroes gain HP.

**Expected behavior**
There should be no ordering decision.

See #1272 for attachments.

**Comment by wrhyme29** [comment]
The Scholar has this same behavior when he is at full HP with Mortal Form to Energy. Here's a save game loaded into Tempest's Use Power phase (no mod content). Just use the Cleansing Downpour power and you will see that same behavior.

[save-undo-21-Tempest-UsePower.zip](https://github.com/SotMSteamMods/CauldronMods/files/6431476/save-undo-21-Tempest-UsePower.zip)

If this is a bug in the base game, I'm happy to adjust Snowshade Gown in whatever is the same way is as you fix it for Mortal Form to Energy

**Comment by MigrantP** [comment]
This will be fixed in the next update - no change should be needed to your cards!
