### ISSUE TITLE
Lady of the Wood and Fall with Lightning Damage not reducing damage on Sonic Mine

### ISSUE THREAD

**Issue by EmptyHach** [SotMSteamMods/CauldronMods#1309]
**Describe the bug**
The Season Fall should make damaged targets do -1 damage, but that isn't working on Sonic mine, who I had previously reduced its damage from Crickets power.

**What does it affect**
Card(s): Fall, Sonic Mine
Deck(s): Lady of the Wood, Ambuscade, Cricket

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**
I expected damaging the Sonic Mine with Lightning would reduce it's damage by -1, as stated on the card Fall.   The Sonic Mine was already at 1hp, so when it was hit with 1 lightning from Lady of the wood it destroyed the Mine, thus setting off it's ability.  The SOnic mine was already doing -1 from Crickets main power, but the -1 from Lady of the Wood was not shown, so the Mine still did 1 damage.  

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by cdallasanta** [comment]
It looks like we're applying the trigger after the damage is resolved, and the card is destroyed -> deals damage before the damage trigger is resolved. I found a way to fix this copying Nitrogen Round's approach. PR incoming once I write tests.
