### ISSUE TITLE
Zephaeren's Compass does not recognize environment Djinn as valid targets

### ISSUE THREAD

**Issue by b-adams** [SotMSteamMods/CauldronMods#1321]
**Describe the bug**

Playing Malichae in the Chasm of a Thousand Nights, the power on Zephaeren's Compass reports "there are no cards that can be chosen" when the only djinn targets in play are environment ones.

**What does it affect**

Card(s): Zephaeren's Compass, High Mhegas, presumably other djinn card in the Chasm
Deck(s): Malichae, Chasm of a Thousand Nights

**To Reproduce**

1. Play Malichae in Chasm of a Thousand Nights
2. Have Malichae play Zephaeren's Compass (and do not play any of Malichae's djinn in the meanwhile)
3. Wait for environment to play a djinn
4. Use the power on Zephaeren's compass
5. Receive "THERE ARE NO CARDS THAT CAN BE CHOSEN" message

**Expected behavior**

When the power on Zephaeren's compass is used, it should be possible to select an environment djinn target in play and place it in Maelichae's hand.

**Screenshots**

**Additional context**

Confirmed to be intended behavior by tosx on Discord #playtesting on 2021-05-07:

> It should work
> If we'd been thinking ahead when Malichae was created we probably would have made it specify it was only his own djinn. But for the Chasm we just decided it was fine, since there are already other examples of cards entering the wrong decks

**Comment by wrhyme29** [comment]
Closed by #1306
