### ISSUE TITLE
Starlight unable to heal

### ISSUE THREAD

**Issue by DaedalusCain** [SotMSteamMods/CauldronMods#1323]
**Describe the bug**

Starlight's Celestial Aura isn't healing. Nightlore Starlight did self damage multiple times while Celestial Aura was in play, and while CA did block the damage, it did not heal her either.

**What does it affect**
Card(s): Celestial Aura, plus a source of self-damage (such as one of her core powers or Golden Astrolabe)
Deck(s): Nightlore Council Starlight

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

Nightlore Council Starlight, with a constellation in play next to Starlight of Terra, used Golden Astrolabe on herself to trigger healing, was made immune to the damage as expected but didn't heal.

**Expected behavior**

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

[multiplayer-log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6473637/multiplayer-log.txt)

**Comment by wrhyme29** [comment]
This was likely due to the DLL incompatibility in v0.4.5. With the new update (you may need to restart the game/steam to get it) it should be resolved. Can you try to recreate this situation with the new version?
