### ISSUE TITLE
Vanish: Flash Recon does not reveal Scion and Aeon Man cards when not with OblivAeon

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1342]
**Describe the bug**
I played Vanish's Flash Recon in battle zone 2, and it only revealed cards from the hero decks and environment deck, not the Scion deck or Aeon Man deck. When I rewound and tried it in battle zone 1, it worked correctly. Both battle zones had a Scion at this point, there were 3 Aeon Men in battle zone 2, and OblivAeon was in battle zone 1. I think it's only revealing from villain decks when you're with OblivAeon.

**What does it affect**
Card(s): Flash Recon
Deck(s): Vanish

**To Reproduce**
1. Play with Vanish in OblivAeon mode
2. Move Vanish to the battle zone without OblivAeon
3. Play Flash Recon

**Expected behavior**
In my case, Flash Recon should have revealed the top cards of the Scion and Aeon Man decks, since both of those decks had targets in battle zone 2.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76876227/119274096-3fa66200-bbdc-11eb-9369-a963991fd75e.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76876227/119274112-5482f580-bbdc-11eb-90af-fc367a93ee84.png">

**Comment by wrhyme29** [comment]
I was not able to replicate this behavior. I created a test where an Aeon Man, a Scion, and Vanish were all in battle zone 2.  Oblivaeon and all other heroes were in battle zone 1. Flash Recons revealed cards from both the scion and aeon men deck. 

As a result, I'm closing this issue, but if you are  able to replicate this in the future, send in a Game Log and Output Log and I can take a look again
