### ISSUE TITLE
Softlock possibly caused by mod content in OblivAeon

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1344]
**Describe the bug**
In an OblivAeon game, I used 1929 Vanish, Lady fo the Wood, and MoSS Lady of the Wood in a play area, finally replacing MoSSLady of the Wood with base Mr Fixer. On his next turn, I tried to use Mr Fixer's Strike power to hit OblivAeon, but when I did the game first gives me the message "We're working on this one!" during the damage preview, then when I select a target it stops progressing. No damage gets dealt, and the game does not continue.

Edit: the same thing happens when I try to use the power on Mecha-Knight with Mr Fixer, and even when I try to use Legacy's power to let Mr Fixer use a power. It does not happen when a different hero uses a power to damage OblivAeon

**What does it affect**
Card(s): Unknown
Deck(s): Unknown

**To Reproduce**
I don't really know what caused this, so I'm not sure how to reproduce it. I included the log so you can see what led up to it.

**Expected behavior**

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/76876227/119280484-9ec99e00-bbff-11eb-91ae-dee50dc866a9.png">

**Logs**
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6529116/log.txt)

**Additional context**
This happened in the same game and the same turn as this other issue I submitted https://github.com/SotMSteamMods/CauldronMods/issues/1343

**Comment by LNBertolini** [comment]
That log doesn't have some of the nitty-gritty details. Could you post the output_log from the same folder, if you still have it?
