### ISSUE TITLE
Missing Art: OblivAeon end-of-game environment images for Superstorm Akela and Windmill City

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1350]
**Describe the bug**
On the end screen of an OblivAeon game, the "environments destroyed" section did not show the two Cauldron environments that were destroyed, Superstorm Akela and Windmill City

**Screenshots**
<img width="1019" alt="Screen Shot 2021-05-28 at 7 34 17 PM" src="https://user-images.githubusercontent.com/76876227/120056574-2736ad00-c00b-11eb-82f7-9b0dbbf863dd.png">
<img width="1021" alt="Screen Shot 2021-05-28 at 7 19 37 PM" src="https://user-images.githubusercontent.com/76876227/120056578-2aca3400-c00b-11eb-8445-2e63641db32f.png">

**Comment by wrhyme29** [comment]
This was due to the workshop push not having all the appropriate art. It will be fixed in the next Workshop release
