### ISSUE TITLE
Byrgs Nail did not find an active hero in the battle zone

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1375]
**Describe the bug**
Necro was in the Second Battle Zone (Vault 5). At the end of his draw phase he triggered Shattered Display Case which discarded Byrgs Nail, and it said there were no active heroes and didn’t work.

Note: Byrgs Nail was played earlier in the game in an empty battle zone, and it said that, which seemed correct for that moment.

**What does it affect**
Card(s): Byrgs Nail (and other artifacts perhaps)
Deck(s): Vault 5

Happened on this stream:
https://www.twitch.tv/videos/1057419969

**Comment by MigrantP** [comment]
Note: these cards might want to say "when played from the environment deck" instead of "the first time in the game" perhaps. They can also end up back in the environment deck if a hero is incapacitated.

**Comment by wrhyme29** [comment]
I like that wording - I'll check with tosx to see if he would be okay with that change.

As for your second point, thats not actually the current behavior, when the artifact becomes owned by a hero, it gets removed with their deck when their cards are removed from the game.
