### ISSUE TITLE
Celestrial Tribunal Won't Judge Us

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#138]
**Describe the bug**
When going through the Representative of Earth card's selection of heroes, no modded heroes are available. 

**What does it affect**
Card(s): Representative of Earth
Deck(s): Celestial Tribunal 

**To Reproduce**
Any game with Celestial Tribunal and Representative of Earth enters play. 

**Expected behavior**
To be able to see a list of mod heroes in addition to the canon ones. 

**Screenshots**

**Additional context**
I recognize this is probably something to do with the game itself, and not the mod. But I figured I'd make the note.

**Comment by Vilnor** [comment]
I did a basic investigation.  Celestial Tribunal would need to be updated to support loading Mod content.  The card itself creates a CardDefinition out of a decklist, a card, and a controller, bypassing the mod loader shim.

it is possible that there's a way to crash/lock the game as I don't see any reason why mod hero's wouldn't be found by the queries.  Maybe just promo's, unclear.

What I'm saying is don't be surprised if we find a way to explode this environment.

**Comment by wrhyme29** [comment]
With new updates from Handelabra, this is no longer an engine limitation. Any future issues with Celestial Tribunal should be reported
