### ISSUE TITLE
Gargoyle: Violent Assist does not prevent damage if a redirect is unresolved

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1397]
**Describe the bug**
Benchmark had Intervening Path Calculator in play, and Gargoyle had Violent Assist in play. Benchmark played Fly-By and selected Gargoyle to be dealt damage. I chose for Violent Assist to take effect first, and selected "yes" to prevent the damage. Gargoyle received the damage boost, but then Benchmark's damage was not prevented.

When I rewound and chose for Intervening Path Calculator to take effect first, selected not to redirect the damage, and then chose for Violent Assist to prevent the damage, it worked was intended. 

**What does it affect**
Card(s): Violent Assist
Deck(s): Gargoyle

**To Reproduce**
1. Play as Gargoyle
2. Have in play Violent Assist and any card that will prompt a redirect away from Gargoyle when dealt damage by a hero target (I had Intervening Path Calculator, but I suspect it's not specific to that card)
3. Have another hero target direct damage at Gargoyle
4. Choose for Violent Assist to take effect before the redirect, and choose to prevent the damage
5. See error

**Expected behavior**
Violent Assist should prevent the damage whether it takes effect before or after the redirect.

**Screenshots**
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/76876227/122853260-f0894500-d2df-11eb-9a2c-79f89408974c.png">
<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/76876227/122853412-30502c80-d2e0-11eb-854d-50c41ff2a7b3.png">
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/76876227/122853440-380fd100-d2e0-11eb-82a1-6d59114e723a.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/76876227/122853451-41993900-d2e0-11eb-979a-ed86862dc056.png">

**Logs**
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/6690628/log.txt)
[Player.log](https://github.com/SotMSteamMods/CauldronMods/files/6690630/Player.log)

**Additional context**
This happened in OblivAeon mode, but there wasn't anything mode-specific going on that would've interfered with these cards. I've attached the logs just in case.

**Comment by wrhyme29** [comment]
This is the same issue as #1117 and #1066 as its prevention effects being overriden by redirection. This is a known issue with the engine

**Comment by wrhyme29** [comment]
We need to put an if(!dda.IsPretend) wrapped around this line:
`SetCardPropertyToTrueIfRealAction("OncePerTurn");`

Then apply the pretend Nightlore Armor fix
