### ISSUE TITLE
Typo with Anathema accelerated evolution and ghost ops tango one.

### ISSUE THREAD

**Issue by Skunkbrains** [SotMSteamMods/CauldronMods#1402]
**Describe the bug**
Into text when AAE is the villain and GOTO is the hero in the first turn order has Anathema saying "his intro says "Still trying to hide? My senses *how* only gotten sharper." instead of have like it was probably intended to.

**What does it affect**
Card(s): Ghost op tango 1, Anathema accelerated evolution.
Deck(s): Ghost OPs Tango 1, Anathema Accelerated evolution.

**To Reproduce**
1. Anathema Accelerated evolution as villain, Ghost OPs tango one as first hero in turn order
2. click play
4. See typo in intro text

**Expected behavior**
No typo? I'm honestly not sure if this should be a bug report at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/87055350/124700936-8b6a4d80-dea2-11eb-90c2-3b83d761e4b1.png)

**Additional context**

**Comment by cdallasanta** [comment]
Filing a bug report was a great way to report this. Thanks!
