### ISSUE TITLE
Ace in the Hole Played offturn

### ISSUE THREAD

**Issue by Rosgath** [SotMSteamMods/CauldronMods#1403]
**Describe the bug**
When played from the top of the deck (Or possibly just out of turn) Ace in the Hold does not allow Baccarat to use his innate power twice on that Power Phase.

**What does it affect**
Card(s): Ace in the Hole
Deck(s): Baccarat

**To Reproduce**
1. Play with Vanish and Baccarat (found with Vanish, could be a problem with another character as well)
2. play the card that allows Vanish to check the top card of each deck, then play 1 (can't remember the name). Make sure Baccarat has Ace in the Hole on top of his deck
3. Play Ace in the Hole. Finish the Power phase.

**Expected behavior**
Ace in the hole plays normally and allows Baccarat to play a card, but does not give the power use.

**Screenshots**
No SS, Sorry :(

**Logs**
No Crash

**Additional context**
I was playing a test game against Baron Blade with Ra, Vanish, and Baccarat. Vanish played a one shot to let Baccarat play a card on her turn (I believe it's Rapid Recon, but I forget the name) and I had him play Ace in the Hole and after ending her Power Phase he did not get  a chance to use his Power.

**Comment by wrhyme29** [comment]
This is working as expected. The card specifies Baccarats power phase,  so if used off turn,  there are no extra powers.

**Comment by wac** [comment]
The ruling from BGG: 
https://boardgamegeek.com/thread/1098704/custom-hero-baccarat-card-art/page/5

Matthew Bishop
DesignerPublisher
@tosx
Posted,Sep 19, 2014
Correct on all counts!
- Graveyard Bridge ends with no copies of the target card left in your trash.
- AitH gives no power use out of turn, and at most 1 additional power during your turn.
