### ISSUE TITLE
Berserker Knight is missing a period at the end of his innate power

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1412]
**Describe the bug**
A good sentence should end with a period, unlike this one

**What does it affect**
Card(s): Berserker Knight
Deck(s): Knight

**Comment by wrhyme29** [comment]
Looking at the decklist and card image, this already has a period at the end of his innate power:

![20210727000054_1](https://user-images.githubusercontent.com/32969943/127098217-c7e316ce-edb9-4978-9ad5-4207e457f0a9.jpg)

Are you sure it was Berserker Knight's innate power you were looking at?

**Comment by MigrantP** [comment]
Yes. If I look at the same thing in my game, there is no period at the end. Perhaps it's been fixed but not released.

**Comment by wrhyme29** [comment]
Yep that looks like exactly what it is. Closing this issue since the new release will fix this issue
