### ISSUE TITLE
Flash Recon did not reveal cards from OA decks

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1428]
**Describe the bug**
Flash Recon was played in a battle zone with Scions and Aeon Men. It did not reveal a Scion or Aeon Men card from their respective decks.

**What does it affect**
Card(s): Flash Recon
Deck(s): Vanish

**Comment by wrhyme29** [comment]
I assume this was from the stream last night? If yes, I'll look to see it happen in action

I already fixed this very issue prior to this release so it shouldn't be happening anymore, especially since I have a passing test for this very thing.

**Comment by MigrantP** [comment]
Yep, this stream - https://www.twitch.tv/videos/1100115084

**Comment by LNBertolini** [comment]
Found the problem - Flash Recon was asking if the deck's battlezone was the same as its own, when IsLocationVisibleToCardSource is sufficient and necessary.
