### ISSUE TITLE
Magic Blade violating battle zone rules

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1429]
**Describe the bug**
Magic Blade was on a hero in the other battle zone (not the battle zone with Dungeons of Terror). It accessed its deck from the wrong battle zone. It should check the environment deck in the battle zone where it is.

**What does it affect**
Card(s): Magic Blade
Deck(s): Dungeons of Terror

**Comment by MigrantP** [comment]
From this stream - https://www.twitch.tv/videos/1100115084

**Comment by wrhyme29** [comment]
This will also affect Delayed Rock Trap and Ring of Foresight
