### ISSUE TITLE
Necro/Malichae - Talisman detaches from Djinn when de-digivolving

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#144]
**Describe the bug**
The Talisman returns to Necro's play area when a Djinn would be destroyed but is saved by destroying an attached Djinn Ongoing.

**What does it affect**
Card(s): Talisman and any djinn with one of its upgrades
Deck(s): Necro and Malichae

**To Reproduce**
1. Start a game with Necro and Malichae
2. Malichae plays a Djinn (e.g. Reshiel)
3. Malichae plays the "High" upgrade of that Djinn (e.g. High Reshiel) as an upgrade
4. Necro plays Talisman attached to Reshiel
5. Damage Reshiel to 0HP. Instead of being destroyed, High Reshiel is destroyed and Reshiel is restored to 5HP. Talisman returns to Necro's play area and is no longer attached to any target.

**Expected behavior**
Talisman remains attached to Reshiel, as Reshiel is still the same target and never left play.

Separately, if Reshiel _had_ left play, Talisman would've remained in Malichae's play area (similar to SkyScraper links)

**Screenshots**

**Additional context**
```
Skinwalker GloomWeaver initiates 3 Melee damage to Reshiel.
Skinwalker GloomWeaver deals Reshiel 3 Melee damage.
Reshiel is now at -1 HP.
Created decision [SelectCard/None D232 Malichae]
Reshiel destroys High Reshiel!
GameController moved High Reshiel to Malichae's trash.
Reshiel caused Reshiel's HP to be set to 5.
GameController moved Talisman to Necro's play area.
```

Additional testing of related things that worked correctly:
* SkyScraper links (e.g. Compulsion Canister) stay attached to the Djinn through the above process.
* Somael's temporary "reduce damage dealt to 1 target until the start of your turn" effect remains on the Djinn through the above process. Presumably other temporary effects applied to a target do so as well.

**Comment by TopherGerkey** [comment]
Just tested this with Malichae and the Stranger. Put Mark of the Blood Leech and High Ezael on Ezael. Killed Ezael. High Ezael was correctly discarded and the rune stayed correctly attached to Ezael.

**Comment by Vilnor** [comment]
de-digivolving :)
