### ISSUE TITLE
Hit point totals display incorrectly for DCStarlight & WRKnight

### ISSUE THREAD

**Issue by cynlover01** [SotMSteamMods/CauldronMods#1454]
**Describe the bug**
The hit point display on the summary screen consistently shows these characters w/"99" collective hit points instead of showing their individual totals, and no matter how many hit points the "character" actually has. 

(I'm sure this must have been noted already, but I didn't see it under known issues...)

**What does it affect**
Card(s): n/a
Deck(s): n/a

**To Reproduce**
Play a game using one or both of these character "teams". 

**Expected behavior**
Ideally, the game should display each character's individual hit point score, as with the SWSentinels (as you can see in the 2nd screenshot). 

**Screenshots**
![DCStarlight_HP_Display_Error1](https://user-images.githubusercontent.com/88640337/128665056-67e7c3e4-9fb7-4d48-a18d-4535a44e32a4.jpg)
![DCStarlight_HP_Display_Error2](https://user-images.githubusercontent.com/88640337/128665068-72e5b479-ddd6-4191-b4b8-50c947965b47.jpg)

**Logs**
n/a

**Additional context**
n/a

**Comment by wrhyme29** [comment]
This is unfortunately an engine limitation we can't get around as a result of the variants having different number of character cards than the base character. At this time, there's nothing we can do about it.
