### ISSUE TITLE
Mark of Breaking not ending up in the right play area in OA mode

### ISSUE THREAD

**Issue by MigrantP** [SotMSteamMods/CauldronMods#1456]
**Describe the bug**
Mark of Breaking was next to Sanction in BZ2. We destroyed Sanction, and Mark of Breaking moved to OblivAeon’s play area in BZ1. It should have stayed in the villain play area of BZ2.

**What does it affect**
Card(s):Mark of Breaking
Deck(s):Stranger

Happened on this stream: https://www.twitch.tv/videos/1121473691

**Comment by origamiswami** [comment]
Just wanted to chime in to say that this happens with Skyscraper's links as well. In the screenshot below, that link in OblivAeon's play area used to be on an Aeon Thrall in Battle Zone 2. So if it's a bug, it's probably a bug in AddIfTheCardThatThisCardIsNextToLeavesPlayMoveItToTheirPlayAreaTrigger() and not a bug in Mark of Breaking.

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/76876227/129972699-683aceda-d8e0-4926-a348-98e54e5e76fa.png">

**Comment by MigrantP** [comment]
Interesting, we can take a look at that!

**Comment by wrhyme29** [comment]
That was my instinct but I hadn't tested with base game content - thanks Origami! @MigrantP let me know if it turns out to be something you think is still on our end and I can dig more
