### ISSUE TITLE
Anathema's Knuckle Dragger doesn't destroy an ongoing if damage is redirected

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1472]
**Describe the bug**
Knuckle Dragger: 
"At the end of the villain turn, Anathema deals the hero character with the highest HP (H)+1 melee damage. If that hero takes damage this way, they must destroy 1 of their ongoing cards."

If the damage is redirected to a different hero, and the hero takes damage, no ongoing destruction is compelled. 

**What does it affect**
Card(s): Knuckle Dragger
Deck(s): Anathema

**To Reproduce**
1. Use this setup

Scholar with Alchemical Redirection in play 
a non-Scholar hero with higher HP than Scholar 
Ongoing cards in play for both relevant heroes. 

2. Play these cards to setup
3. Play the problem card

Trigger End of Turn phase for Anathema with Knuckle Dragger in play. 

Damage will be redirected to Scholar. 
Scholar will take damage. 
No ongoing destruction will be compelled. 

**Expected behavior**
per tosx, "The intent is damage = destruction"

Maybe rephrasing the card as "If A hero takes damage this way [...]" if we're OK with changes like that?

**Comment by wrhyme29** [comment]
After discussions in Discord, QuagmaBlast and I both believe that RAW this effect is implemented correctly. Clearly, tosx believes that RAI is different in this case. Unless tosx approves a wording change on this card, we don't think a change is necessary. I will close this issue. We can keep it for reference in the future to review again later.
