### ISSUE TITLE
The Stranger - only one Glyph is preventing self-damage from Runes

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#148]
**Describe the bug**
Only the first instance of the Stranger's Rune self-damage seems to be being prevented by Glyphs, even when there are multiple Glyphs in play.

**To Reproduce**
1. Play 2 or more Runes as the Stranger.
2. Play 2 or more Glyphs as the Stranger.
3. At the beginning of his turn, choose not to destroy any Runes.
4. Only the first instance of damage will offer the choice to prevent.

**Expected behavior**
Glyphs can prevent "any one" instance of self-damage by the Stranger. With 2 Runes and 2 Glyphs in play, the Stranger should be able to keep everything in play and choose to take no self-damage.

**Additional context**
It's possible that the Glyphs are looking for the first instance of self-damage in a turn, rather than any instance of self-damage?

**Comment by DireAvenger20** [comment]
I had a game where the Glyphs were working as intended and were blocking the self-damage of multiple runes (with multiple Glyphs in play) but then in a later game, it was acting like reported above and only working on the first rune. Not sure why it changed/was different between games.

**Comment by DireAvenger20** [comment]
Not sure whether or not to create a new issue, but was playing the Stranger again and was able to block the start of turn damage of two runes (Twisted Shadow and Binding) with only one Glyph in play (Glyph of Combustion).

**Comment by DireAvenger20** [comment]
To make it weirder, I had a case where I had 5 runes and two glyphs (Combustion and Decay) in play. Combustion let me prevent the first 3 self-damages, then stopped working for the rest, however Decay never gave me an option to prevent damage.
