### ISSUE TITLE
Renegade Cricket: Dark Mind steals card, Cricket steals it back

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1507]
**Describe the bug**
This is a similar situation to [issue 1038](https://github.com/SotMSteamMods/CauldronMods/issues/1038), but it's not the same issue. When you use Renegade Cricket's base power to reveal an ongoing card while in the same BZ as Dark Mind, the ongoing gets put under Dark Mind. However, you are then given the option to discard a card to put it into play. If you do, it goes into play despite being underneath Dark Mind. If you don't discard, it goes into the player's hand despite being underneath Dark Mind. 

**What does it affect**
Card(s): Renegade Cricket
Deck(s): Cricket

**To Reproduce**
1. Have Renegade Cricket in the same battle zone as Dark Mind
2. Use Cricket's base power to reveal an ongoing card from a hero deck
3. After Dark Mind steals the ongoing card, you will be prompted to discard a card or skip
4. Whichever choice you make, the card gets removed from under Dark Mind

**Expected behavior**
Given how Great Fortune and Form the Mecha-Knight interact with Dark Mind, I think Cricket should be unable to do anything with the revealed card after Dark Mind steals it.

**Comment by wrhyme29** [comment]
Interestingly there are unit tests written and code specifically to grab the card back from Dark Mind. I'm curious to why that is the case, as I'm inclined to agree with you about that behavior
