### ISSUE TITLE
Playing Mark for Execution Stops Game

### ISSUE THREAD

**Issue by NinjaMonkey1234** [SotMSteamMods/CauldronMods#1508]
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/7402970/output_log.txt)

While playing a game against Anathema, when I played Mark For Execution, the game stopped and did not move forward to the Power phase. I've attached the output log and an image showing who all is in play.

![image](https://user-images.githubusercontent.com/28448033/138557344-e942cc08-84ba-4197-b3e1-359d1aacdb93.png)

**Comment by wrhyme29** [comment]
This is an issue that stems from a recent update to the base game engine. I believe this has been resolved in one of the recent updates, or if not, Handelabra is aware of it and will be fixing it soon.
