### ISSUE TITLE
Ace in the Hole doesn't trigger power uses when played out of turn

### ISSUE THREAD

**Issue by ever-3W** [SotMSteamMods/CauldronMods#1520]
**Describe the bug**
Ace in the Hole doesn't trigger power uses when played outside of Baccarat's turn (with Argent Adept, Legacy, etc.)

**What does it affect**
Card(s): Ace in the Hole
Deck(s): Baccarat

**To Reproduce**
1. Set up a game with Baccarat and something that gives out of turn plays
2. Have Ace in the Hole be played outside Baccarat's turn

**Expected behavior**
The player should be prompted if they want to use Baccarat's power twice this turn (similar to Mr Fixer's Overdrive)

**Screenshots**

**Logs**

[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/7446650/output_log.txt)
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/7446652/log.txt)

**Additional context**

**Comment by wrhyme29** [comment]
This is the correct behavior. Ace in the Hole says "You may use Baccarat's innate power twice during **your power phase** this turn. When played out of turn, Baccarat does not have a power phase.

Closing this issue, but feel free to ask any questions you may have
