### ISSUE TITLE
Variant Anathema on Random don't show opening screen dialog

### ISSUE THREAD

**Issue by DustanBower** [SotMSteamMods/CauldronMods#1523]
**Describe the bug**
On his variant, Anathema shows no text on the opening screen if he was randomly selected, but shows normal text if he was specifically selected.

**What does it affect**
Card(s):
Deck(s): Anathema

**To Reproduce**
1. Randomize until you have variant Anathema
2. Start game

**Expected behavior**
Anathema shows normal startup text in the opening screen.

**Screenshots**
https://drive.google.com/file/d/15vrxRdih60CgxDAXYg-pQAmWH3KJzLtP/view?usp=sharing
**Logs**
https://drive.google.com/file/d/1e5ha4O5t-kEGhIgpca7R5fjRS3pID8Yx/view?usp=sharing

**Additional context**

**Comment by wrhyme29** [comment]
This is an issue with the base game logic of selecting random and resulting in variants of mod villains. Handelabra is aware of the issue.
