### ISSUE TITLE
The Ram - Up Close Power activates whether I choose it or not

### ISSUE THREAD

**Issue by LordRutabaga** [SotMSteamMods/CauldronMods#1524]
**Describe the bug**
When Up Close is attached to a character card, I cannot use that hero's base power. Both the 'Use First Power' and 'Use Second Power' buttons activate Up Close's power.

**What does it affect**
Card(s): Up Close
Deck(s): The Ram

**To Reproduce**
1. Select The Ram as the villain and choose any combination of heroes and environment
2. Allow Up Close to come into play and attach to a hero
3. Attempt to use that hero's power
4. Up Close's power will activate instead

**Expected behavior**
I should be able to activate either Up Close's power or the hero's base power.

**Screenshots**

https://user-images.githubusercontent.com/74675452/139790813-c00d5661-bd85-45ac-a538-ff9449f55a66.mp4

**Logs**
N/A

**Additional context**
N/A

**Comment by wrhyme29** [comment]
This is a bug in the base game. Handelabra is aware of the issue
