### ISSUE TITLE
Baccarat - Bring Down the House

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#153]
**Describe the bug**
The special-string help text for Bring Down the House says "There are no cards cards" when the trash is empty.
![2020-11-21](https://user-images.githubusercontent.com/74736587/99884326-17b95000-2bf3-11eb-8674-3b7ea2734d6c.png)

**Comment by mgirman520** [comment]
With the next update it will read "No pairs of cards"
