### ISSUE TITLE
Necro Variant Incap moves the cards it plays out of hand before playing them

### ISSUE THREAD

**Issue by bobbertoriley** [SotMSteamMods/CauldronMods#1539]
**Describe the bug**
Necro: Last of the Forgotten Order's third incap ability says "play 2 cards at random from their hand." However, the play location of the played cards is actually "revealed location"

**What does it affect**
Card(s): Necro: Last of the Forgotten Order variant

**To Reproduce**
1. Incapacitate Necro: Last of the Forgotten Order
2. Use Necro's 3rd incapacitated ability on a hero.

**Expected Behavior:**
Any cards played by this incap effect are played from the hand

**Additional context**
The Hero Charade from Menagerie of the Multiverse (https://steamcommunity.com/sharedfiles/filedetails/?id=2616657693) cares about what location her cards are played from. As written, Necro's incap ability should not trigger any bonus effects on her cards. However, the utility function used by this method moves all cards to a RevealLocation. Because of this, the cards are played from a location other than Charade's hand, and the bonus effects are applied.

**Comment by wrhyme29** [comment]
I can change this but be aware that the base game uses the revealed location like this for random plays (see Return with the Dawn's `BringCitizenBackResponse` method, so thats likely going to face some similar interactions there.

**Comment by bobbertoriley** [comment]
Turns out wrhyme is right about checking where it played from. Akash'Thriya's Primordial seeds are a good example of how to handle the reveal zone moving a card before playing it.

Closing the issue as no longer necessary.
