### ISSUE TITLE
Mistress of Fate ends incap hero effects on revive

### ISSUE THREAD

**Issue by ever-3W** [SotMSteamMods/CauldronMods#1561]
**Describe the bug**
When MoF revives a hero that used a "Until the start of your next turn..." incap ability, the effect ends immediately instead of at the start of their next turn.

**What does it affect**
Card(s): (Villain Character Card)
Deck(s): The Mistress of Fate

**To Reproduce**
1. Have one or more heroes incapacitated
2. On their turn, use an ability that expires at the start of their next turn

**Expected behavior**
The effect should persist until the start of the hero's next turn.

**Screenshots**
![20220207100222_1](https://user-images.githubusercontent.com/42660111/152816832-b34e90eb-b065-419d-b6f1-d482a4613acd.jpg)

**Logs**
Relevant user log sections:
```Day of Sinners was flipped to its back side.
Created decision [SelectCard/None D99-2]
Day of Sorrows was flipped to its back side.
Created decision [SelectCard/None D99-3]
Day of Swords was flipped to its back side.
The Mistress Of Fate moved To Dust from the villain trash to out of game.
The top card of the villain deck was flipped face-down.
The Mistress Of Fate moved one of The Mistress Of Fate's cards from the villain deck to out of game.
The top card of the villain deck was flipped face-down.
The Mistress Of Fate moved one of The Mistress Of Fate's cards from the villain deck to out of game.
The top card of the villain deck was flipped face-down.
The Mistress Of Fate moved one of The Mistress Of Fate's cards from the villain deck to out of game.
The top card of the villain deck was flipped face-down.
The Mistress Of Fate moved one of The Mistress Of Fate's cards from the villain deck to out of game.
Created decision [SelectCards/None D100]
Created decision [SelectCard/None D100-1]
Lady Of The Wood was flipped to its front side.
Notice: an ongoing effect just expired: Increase Melee damage dealt by 1.
Made Lady Of The Wood a target with 22 max HP and 22 current HP.
The Mistress Of Fate moves 32 cards cards to the top of Lady Of The Wood's Deck.
The Mistress Of Fate moves 6 cards cards to the top of Lady Of The Wood's Hand.

...

Went from Haka's PlayCard phase to UsePower phase. 
Created decision [UsePower/UsePower D119 Haka]
The Eternal Haka uses the power on Mere.
Created decision [SelectTargets/None D120 Haka]
Created decision [SelectTarget/None D120-1 Haka]
The Eternal Haka initiates 2 Melee damage to The Mistress Of Fate.
The Eternal Haka deals The Mistress Of Fate 2 Melee damage.
The Mistress Of Fate is now at 83 HP.
Shinobi Assassin prevented Haka from drawing cards.
Shinobi Assassin puts Shinobi Assassin into play.
Shinobi Assassin initiates 3 Melee damage to Hour Devourer.
DealDamageAction of Shinobi Assassin was cancelled by Ground Pound.
Haka draws Ground Pound.
Went from Haka's UsePower phase to DrawCard phase. 
Haka draws Vitality Surge.
Went from Haka's DrawCard phase to End phase. 
Went from Haka's End phase to Lady Of The Wood's Start phase. 
Went from Lady Of The Wood's Start phase to PlayCard phase. 
```

[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/8016410/output_log.txt)

**Additional context**

**Comment by wrhyme29** [comment]
I've determined that this is a base game bug, and I've reported it to MigrantP. Thanks for the report!

**Comment by wrhyme29** [comment]
According to MigrantP, this is the intended behavior:

"Looking into this, it's not a bug based on previous rulings from Christopher. From the fireside chats:

Suppose Sky-Scraper is incapacitated and has used the “become a target” incapacitated ability. If she is revived using Rites of Revival, the 1 HP indestructible target status is wiped, and she is her regular self at 8 HP with a 33 HP max and is fully destructible. **Rites of Revival essentially resets the character, starting anew.**"

The bolded line is the key sentence that led to the implementation Handelabra used.
