### ISSUE TITLE
Baccarat Graveyard Bridge

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#157]
**Describe the bug**
When playing Graveyard Bridge, the UI asks the player to choose a card to put on the very top of the deck. 

**What does it affect**
Card(s): Graveyard Bridge
Deck(s): Baccarat

**To Reproduce**
Playing Graveyard Bridge

**Expected behavior**
The card to just shuffle the appropriate cards into the deck without a pop up - there's no reason for me to choose any card in this scenario because all affected cards are going to be shuffled in regardless. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74740837/99886649-2bfd4d00-2bf3-11eb-92b5-b639178c50f7.png)

**Additional context**
Despite the read out, the card play does not actually put the cards on the top of the deck, they are actually shuffled in.

**Comment by TopherGerkey** [comment]
The bit about the confirmation prompt affects lots of cards currently, see issue #150. 

Don't you have to select at least one card for this to work? Unless those three cards are the only ones in the trash, I guess...

**Comment by mgirman520** [comment]
With the next update it will just shuffle the cards.
