### ISSUE TITLE
Tak Ahab is not properly discarding cards under him for the purposes of Shipshape

### ISSUE THREAD

**Issue by LemeeAdams** [SotMSteamMods/CauldronMods#1582]
**Describe the bug**
Tak Ahab is not properly discarding cards under him for the purposes of Shipshape.

**What does it affect**
Card(s): Tak Ahab
Deck(s): Northspar

**To Reproduce**
1. La Comadora in Northspar
2. Play Shipshape
3. Tak Ahab enters play and grabs the top of La Comadora's deck.
4. When he discards it, she doesn't get the draw from shipshape.

**Additional context**
She definitely didn't discard a card earlier that turn.

**Comment by origamiswami** [comment]
I think this is actually correct behavior. Shipshape says "The first time YOU discard a card this turn, you may draw a card." Tak Ahab discarding a card should not trigger that. This is consistent with how Shipshape interacts with other base-game content.

**Comment by LemeeAdams** [comment]
I don’t think so. Like, if setback discarded the top card of her deck, I think she should draw a card. I haven’t tested it, but I don’t think the “you” is a meaningful distinction. If a villain makes her discard from hand, she draws, and I know that works.

**Comment by origamiswami** [comment]
Just tried it in-game and in a unit test with Fumbling Fool, and La Comodora did not draw when Setback discarded the top card of her deck. I'm not sure where to find the ruling, but I'm almost certain this is correct. It's the whole reason the MoveCard() method has the argument ResponsibleTurnTaker.

**Comment by LemeeAdams** [comment]
Oh alright. Well thank you!
