### ISSUE TITLE
Celadroch card bugs.

### ISSUE THREAD

**Issue by Lunaraia** [SotMSteamMods/CauldronMods#1609]
**Describe the bug**
Celadroch has 2 bugs right now that I have found;

1. Night Under The mountain is behaving weirdly. It self-destructs itself during the same turn it is played when a card other than itself tries to play a card. Likewise, the damage increase for it does not reset at the end of the villain turn.
2. Celadroch himself is supposed to be dealing the damage from Gallows Blast, but hitting Celadroch with effects that's supposed to lower damage does not affect Gallows Blast at all.

**What does it affect**
Card(s): Gallows Blast and Night Under The Mountain.
Deck(s): Celadroch's Villain Deck.

**To Reproduce**
1. Play normally and somehow survive long enough for him to actually use the cards.
2. The best way to do this is to use mass damage mitigation + redirects, for a short while at least.
3. Fall + Shawl from Lady of the Woods makes for an easy check for the damage reduction, while you just need to survive long enough to see the weirdness with Night Under the Mountain.
4. Play the problem card
5. See error

**Expected behavior**
One would expect Night Under The Mountain to not blow itself up to play itself multiple times, likewise I would expect Gallows Blast to be affected by damage reduction.

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by wrhyme29** [comment]
The issue with the Night Under the Mountain buff was that it was set to expire on the Next End Phase, but that by default excludes the current one if it is actively the villains turn. As a result, it was sticking around for 1 round past when you would expect it to. I've fixed that accordingly. Looking into the other things now.

**Comment by wrhyme29** [comment]
For the Night Under the Mountain destroying itself, I don't believe that is a bug. Rather, I think Night Under the Mountain is being played in the Start Phase of Celadroch's turn. Resulting in the Night Under the Mountain to destroy itself once the chains of the card it plays have resolved.

**Comment by Lunaraia** [comment]
The destruction took place for me while plays were still ongoing. It was played, destroyed itself was played again then blew up during the end for a total of 11 damage per gallows blast, since the bonus from the turn prior was still active. And there was no effect active to play cards during the villain end phase as I had stashed all of his servants under savage mana, which, btw is mandatory if you wish to have any hope of beating him. In fact, Gallows Blast alone is enough to prevent any hope of victory for most setups, it's that powerful a card.

**Comment by wrhyme29** [comment]
All of that tracks, if you assume its initial play of Night Under the Mountain was in the Start Phase of Celadroch's turn. I've done testing and it doesn't blow itself up immediately if it is played during the Play Phase.

Here's an example of the behavior:

--Beginning of Start Phase--
1. Remove a storm token, resulting in playing the top card of the villain deck
2. Night Under the Mountain is played, resulting in playing the top card of the villain deck
3. Spring's Atrophy is played, resulting in all other elemental's being played by Celadroch
4. Summer's Wrath, Winter's Bane, and Autumn's Torment each enter play.
5. Now that the chain of plays from Night Under the Mountain is done, it realizes that it is currently the Start Phase, so it destroys itself.
--End of Start Phase--

**Comment by Lunaraia** [comment]
The wording suggest it will blow itself up at the start of the next villain turn, which will throw most people for a loop. Especially since night under the mountain is guaranteed to be played from turn 6 outward due to how the minions work. There are cards for other villains that have similar wording, can be played during the start phase and doesn't blow itself up that turn, which means it's consistent with its wording, but not with the remaining cards.

**Comment by wrhyme29** [comment]
As for Gallow's Blast, I am not observing the same behavior as you for reduction effects. When I apply a reduction effect to Celadroch, Gallow's Blast's damage is correctly reduced.

**Comment by Lunaraia** [comment]
Weird, I hit him with 2 shots of lightning from Lady and I still took the full blast with no reductions from Fall.

**Comment by wrhyme29** [comment]
The destruction at start of turn trigger is coded with the same exact code as cards in the core game. All cards with this effect would have the same property if played during the start phase.

**Comment by Lunaraia** [comment]
For Night Under the mountain, essentially most of the "start of turn" triggers would trigger at the beginning of the "start of turn" part not the end, thus only blowing up the following turn.

**Comment by Lunaraia** [comment]
In that case, I can only say that Cal here is mathematically unbeatable. Between the damage boosts from night, combined with ever-increasing damage from caels own AoE and 2 gallows blasts that will hit every damn turn once all the minions are out of his deck, there is simply no setup that can survive long enough to take him down.

You need 5+ damage to deal 1 damage to him, and have the ability to mitigate 11+ damage across all heroes every turn. And that's provided you have taken out all his minions and pillars. There is no setup in the entirety of sentinels that can do that.

**Comment by wrhyme29** [comment]
Where you are mistaken is the fact that the beginning of the "start of turn" hasn't finished. 

Card A has Trigger A that happens at start of villain turn, resulting in Card B which has a trigger (Trigger B) that destroys itself at the start of the villain turn.

Trigger A gets evaluated -> Card B adds Trigger B to the stack -> Trigger B gets evaluated.

It's slightly more complex than that under the hood, since different Trigger Types have a set order they are evaluated at, but for the purpose of this discussion, those are irrelevant

**Comment by Lunaraia** [comment]
Fair enough, I can't code to save my life, so I will take your word for it.

**Comment by wrhyme29** [comment]
There are many resources people have created about how to beat Celadroch - heck some people have beaten him on Ultimate! (not me, frankly I've never beaten him). I would recommend asking questions in the Discord or looking at some of the Cauldron forums (https://boardgamegeek.com/thread/1546124/custom-villain-celadroch-card-art) which might give you some insight on how to beat him

**Comment by Lunaraia** [comment]
I have a few more ideas myself, but I have tried most hero combinations that have even slight survivability in face of massive damage and most of them fold once the gallows blasts start going on repeat.

**Comment by wrhyme29** [comment]
I've put in a fix for the buff lasting too long, the rest I think we are in the clear for. Thanks for the report!

**Comment by Lunaraia** [comment]
You're welcome, and thanks.
