### ISSUE TITLE
Halberd - Halberd-06: Foamcore reduces damage to all lowest targets, doesn't prompt

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#161]
**Describe the bug**
When Halberd-06 is in play, it doesn't give players the choice when determining what hero targets are considered "lowest HP" even in the case of a tie. 

**What does it affect**
Card(s): Halberd-06
Deck(s): Halberd

**To Reproduce**
Playing with Halberd-06

**Expected behavior**
The card would give us the choice to decide what is currently the "lowest" hp in the case of ties like Legacy's Landing Pad.

**Screenshots**

**Additional context**

**Comment by Vilnor** [comment]
Investigated issue and confirmed.
Foamcore's trigger will need to be re-written as a custom DealDamageAction trigger similar to how TheWraith's SmokeBombs or Freedom Tower's Legacy Landing pad are implemented.

**Comment by qoala** [comment]
Oh, just noticed that Ether has a similar issue for highest HP hero target. Will check for any others tomorrow.
