### ISSUE TITLE
Tango One - Chameleon Armor/Critical Hit and other damage immunity

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#162]
**Describe the bug**
Two issues with presumably similar fixes:

(A): When Tango One has another source of damage immunity, the damage preview shows the damage has already been prevented before Chameleon Armor's Y/N prompt. The player is able to discard a card to prevent the already-prevented damage.

(B): When Tango One initiates damage against a target who is immune to damage, the damage preview shows the damage has already been prevented before Critical Hit's Y/N prompt. The player is able to discard a card, even though no damage will be dealt.

**What does it affect**
Card(s): Chameleon Armor, Critical Hit
Deck(s): Tango One

**To Reproduce**
Steps to reproduce behavior A:
1. Play Chameleon Armor
2. Use another effect to make Tango One immune to damage, either in general or for a specific type (e.g. Ghost Reactor or Legacy's Heroic Interception)
3. Initiate damage to Tango One of a type to which she is immune.
4. See the Y/N prompt for Chameleon Armor.

Steps to reduce behavior B:
1. Play Critical Hit
2. Have a target that is immune to damage, either in general or for a specific type (e.g. cloaked Ambuscade, betraying a hero protected by Heroic Interception)
3. Initiate damage from Tango One to the immune target
4. See the Y/N prompt for Critical Hit

**Expected behavior**
(A): A "which effect should take effect first" between the other immunity source and Chameleon Armor (similar to the choice between Absolute Zero's Null-Point Calibration Unit and another source of damage immunity or a redirection). If the other source is chosen to take effect first, Chameleon Armor should not offer to discard a card.

(B): Critical Hit should not offer to discard a card. (damage boosts/reductions are usually skipped if the damage instance is entirely prevented due to immunity)

**Screenshots**

**Additional context**

**Comment by qoala** [comment]
Additionally, for Critical Hit, if you discard a Critical card, the +3 damage is applied _through the target's damage immunity_.

**Comment by TopherGerkey** [comment]
Critical Hit is also not reflecting the +3 in the damage total when a critical card is discarded. The message pops up fine, but the total damage score doesn't get updated with that last +3.
