### ISSUE TITLE
Tiamat Heads do not flip when at or below 0 HP (in both SOTM and SOEP)

### ISSUE THREAD

**Issue by mredgecase** [SotMSteamMods/CauldronMods#1627]
Haven't tested in SOTM. 

Logs: 
[Player.log](https://github.com/SotMSteamMods/CauldronMods/files/11583664/Player.log)
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/11583666/log.txt)

Issue persists into SOTM: 
[Player.log](https://github.com/SotMSteamMods/CauldronMods/files/11583690/Player.log)
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/11583692/log.txt)

**Comment by jamespicone** [comment]
Believe this has been fixed and was related to the engine change to the FlipCardAction constructor.
