### ISSUE TITLE
Tango One - One Shot One Kill QoL

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#163]
**Describe the bug**
One Shot, One Kill should tell you how many cards you have in hand before you play it.

**What does it affect**
Card(s): "One Shot, One Kill"
Deck(s): Tango One

**To Reproduce**
1. Have OneShotOneKill in hand
2. Right-click on the card to inspect it.

**Expected behavior**
There should be a "Tango One's hand has X cards" tip, similar to the one on Haka's Haka cards.

Just a quality of life improvement as on the player's own turn, it becomes harder to find the number of cards in their hand without manually counting.

**Screenshots**

**Additional context**

The same likely applies to Lady of the Wood's Calm Before the Storm

**Comment by breenyoung** [comment]
Fixed in #170
