### ISSUE TITLE
Hydra Tiamat breaks on rewind

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#1638]
**Describe the bug**
Playing against Hydra Tiamat, after defeating two of the three initial heads and bringing out the heads underneath them, I rewound the game to a time after the new heads were brought out. The new heads then moved back under the original heads.

**What does it affect**
Card(s): Hydra Tiamat
Deck(s): Tiamat

**To Reproduce**
1. Play against Hydra Tiamat
2. Defeat one or more of the original heads
3. Rewind the game to a time when the new heads were out

**Expected behavior**
The heads should stay in play

**Logs**
[Player.log](https://github.com/SotMSteamMods/CauldronMods/files/11997093/Player.log)

**Comment by origamiswami** [comment]
I tried removing that start of game trigger from TiamatSubCharacterCardController and renaming MoveStartingCards() to StartGame() in a local version, that seems to be working perfectly in normal games and in Boss Rush. Something is throwing an error when I try to run Tiamat's unit tests though, so I could be missing something.

**Comment by jamespicone** [comment]
AFAICT you have correctly identified the issue and the fix. Unit tests run fine for me. I'll put up a pr.
