### ISSUE TITLE
Phase`s " Reinforced Wall " is counted as a character card.

### ISSUE THREAD

**Issue by Daldalus** [SotMSteamMods/CauldronMods#1701]
**Describe the bug**
Phase`s Reinforced Wall is counted as a character card making it immune to many cards.

**What does it affect**
Card(s): Reinforced Wall,
Deck(s): Phase, various hero decks such as Tempest, Tango-one and the argent Adept

**To Reproduce**
1. Play phase 
2. Play any hero card that effects villan cards but not character cards, such as Tempests's into the stratosphere or Tango ones's Sniper Rifle destroy ability.
3. attempt to target the Reinforced Wall 
4. The reinforced wall is not a legal target

**Expected behavior**
The Reinforced Wall should be able to be targeted

**Screenshots**
![20241010095810_1](https://github.com/user-attachments/assets/f4a5361d-65a5-467f-aece-4b0b683653e1)
![20241010124355_1](https://github.com/user-attachments/assets/a07b645f-418e-488a-bb31-3e22622669b2)

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by origamiswami** [comment]
This is because Reinforced Wall is indestructible while it has more than 0 HP. If you play Lady Liberty's Ring the Bell, it doesn't target Reinforced Wall, so the game does not consider it a character card.

**Comment by Daldalus** [comment]
Thank you for pointing that out. My mistake and my apolgoies.

**Comment by Daldalus** [comment]
Thank you for pointing that out. My mistake and my apolgoies.

**Comment by origamiswami** [comment]
No worries, thanks for being on the lookout for issues
