### ISSUE TITLE
Starlight - Stellar Wind

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#177]
**Describe the bug**
Not sure this is a bug, but should this card have a "choose for me" option when there are multiple targets, or do we always want to force manual choices because the targets can include hero targets as well?

1. Play Constellations next to at least two targets
2.. Play Stellar Wind

**Comment by Vilnor** [comment]
The argument to allow the Choice for me is off by default, so yes, please report cases like this.

**Comment by LNBertolini** [comment]
It looks like "Choose for me" will always hit as many targets as possible. It's possible to make the option conditional, though, so I'll have it only show that button if either you have Celestial Aura out or there are no constellations on hero targets.
