### ISSUE TITLE
Blackwood Forest - Dense Brambles

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#178]
**Describe the bug**
Could probably use a special string to display which four targets are currently immune to damage.

**To Reproduce**
1. Environment plays Dense Brambles
2. Right-click Dense Brambles

**Expected behavior**
An info box explaining which targets are being affected by this card would be super useful.

![2020-11-22](https://user-images.githubusercontent.com/74736587/99908860-af2daa00-2caa-11eb-9b4f-0275c7995683.png)

**Comment by TopherGerkey** [comment]
Additionally when attacking a target affected by Brambles, check out the damage calculation.

![2020-11-22 (1)](https://user-images.githubusercontent.com/74736587/99908972-4eeb3800-2cab-11eb-9e0a-f5d3c3de63d9.png)

**Comment by breenyoung** [comment]
> Additionally when attacking a target affected by Brambles, check out the damage calculation.
> 
> ![2020-11-22 (1)](https://user-images.githubusercontent.com/74736587/99908972-4eeb3800-2cab-11eb-9e0a-f5d3c3de63d9.png)

Was spun out into a separate issue #258
