### ISSUE TITLE
Blackwood Forest - Desolation

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#179]
**Describe the bug**
Asks the player if they want to discard Desolation

**To Reproduce**
1. Have the environment play Desolation

**Expected behavior**
Should ask if the player wants to discard cards from their hand.

**Screenshots**
![2020-11-22 (2)](https://user-images.githubusercontent.com/74736587/99909103-244daf00-2cac-11eb-88eb-d7b9219b9fe9.png)

**Comment by breenyoung** [comment]
Resolved in #269
