### ISSUE TITLE
Starlight - Nightlore Armor

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#180]
**Describe the bug**
Asks the player if they want to destroy Nightlore Armor to prevent damage.

**To Reproduce**
1. Have Nightlore Armor in play.
2. Have a hero target other than Starlight take damage.

**Expected behavior**
It should be asking if the player wants to destroy a constellation.

**Screenshots**
![2020-11-22 (3)](https://user-images.githubusercontent.com/74736587/99909172-9c1bd980-2cac-11eb-8029-f8c68fe18a1b.png)

**Comment by LNBertolini** [comment]
That's not possible, unfortunately, the best I can do is "Do you want to prevent the damage?"
