### ISSUE TITLE
Stranger - Mark of Destruction QoL

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#191]
When selecting the card to put Mark of Destruction next to, it would be great if the options were all non-hero targets with the option to "see all targets" like picking a target to damage usually is. Most of the time, you want to put the Mark next to a non-hero target and it's a pain scrolling past hero ongoings and other hero cards. But still want to leave to option to put next to a hero card, just in case.

**Comment by Vilnor** [comment]
Similiar base cards such Compulsion Canister work the same way and since mark of Destruction can be played next to ongoings the targeting options are larger.
For now there's no way to change this behavior, closing as base engine limitation.
