### ISSUE TITLE
Heavy Carapace didn't strike back

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#192]
**Describe the bug**
Heavy Carapace didn't cause backlash damage to Sabre Battle Drone when it hit. 

**What does it affect**
Card(s): Heavy Carapace
Deck(s): Anathema

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**
The Heavy Carapace to hit back at the drone once it hit with 2 melee damage. 

**Screenshots**

**Additional context**

**Comment by qoala** [comment]
Heavy Carapace accidentally had the display text of Razor Scales. The carapace provides damage reduction for villain targets, not revenge damage.

Card text has been fixed in #187
