### ISSUE TITLE
Doc Havoc - Brawler soft locks

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#213]
**Describe the bug**
Breath Stealer is causing a game hang, which I can back out of but not progress through. It's being caused by Doc Havoc using Brawler to attack it. Additionally it's causing a display bug of some kind (see screenshot).

**To Reproduce**
1. Breath Stealer in play and attached to a hero.
2. Aqueducts in play so Breath Stealer is theoretically damageable
3. Doc Havoc uses the power on Brawler
4. Display error and game hangs

**Expected behavior**
In the exact scenario above the Breath Stealer should take  damage and be destroyed. Obvs the game should not hang.

**Screenshots**
![2020-11-23 (2)](https://user-images.githubusercontent.com/74736587/100024369-3adb2f80-2dac-11eb-9723-fd40b4470e35.png)

**Additional context**
Cauterize was in play and I *am* getting the healing prompt in between the damage to Doc Havoc and the game hang.

**Comment by TopherGerkey** [comment]
Feel free to close this as it's almost certainly Gray's fault.

**Comment by Vilnor** [comment]
Root cause is incorrect CardSource on Doc Havoc
