### ISSUE TITLE
Twisting Passages isn't Increasing Damage

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#214]
**Describe the bug**
Twisting Passages in play is not increasing hero damage when there are fewer than two environment targets in play. 

**What does it affect**
Card(s): Twisting Passages
Deck(s): St. Simeon's Catacombs

**To Reproduce**
Have Twisting Passages in play. 

**Expected behavior**
Damage from heroes to be increased. 

**Screenshots**

**Additional context**
There weren't any environment targets in play - only Twisting Passages and Panic.

**Comment by TopherGerkey** [comment]
#209

**Comment by TheRealTails** [comment]
I just realized, Twisting Passages increased damage when there were 2 environment targets in play. So maybe the code on the card is wrong in that it thinks the wording is "there must be at least 2 environment targets in play."

**Comment by Vilnor** [comment]
Thank you for the report, closing as duplicate to #209.
