### ISSUE TITLE
Tiamat - Element of Lightning

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#215]
**Describe the bug**
While it correctly made the proper target skip their draw phase, it didn't prevent a draw via other effects.

**To Reproduce**
1. The Knight has the Maiden's Favor in play.
2. Tiamat plays Element of Lightning and the Knight is chosen to disable his drawing
3. On the Knight's turn, he uses the power on Maiden's Favor, plays an equipment card, and then successfully draws a card.
4. Element of Lightning then causes the Knight to skip his draw phase.

**Expected behavior**
Element of Lightning should prevent ALL card drawing until the villain's next turn

**Comment by Vilnor** [comment]
This is a bug stemming from a engine limitation.  There's no CannotDrawCardsStatusEffect, and the PreventPhaseActionStatusEffect only prevents the end of turn draw.
