### ISSUE TITLE
St Simeon's - Coal Kid

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#216]
**Describe the bug**
Coal Kid somehow did fire damage to Legacy while the latter was immune to fire via Next Evolution.

**To Reproduce**
1. Legacy plays and uses Next Evolution, selecting fire damage.
2. Coal Kid and Aqueducts are in play.
3. Coal Kid deals fire damage to Legacy.

**Expected behavior**
Coal Kid's attack shouldn't go through immunity.

**Comment by TopherGerkey** [comment]
Also, while Aqueducts is still in play, Coal Kid is not appearing in the list of possible targets for attacks.

**Comment by TopherGerkey** [comment]
Figured it out - the card is backwards, and it's only being affected by hero card if Twisting Passages IS out, rather than only if it's NOT out.

**Comment by TheRealTails** [comment]
To add to this one - Coal Kid is also not taking damage from Sacrificial Shrine when that's in play, so it's not just hero damage that is being prevented here.
