### ISSUE TITLE
Blackwood Forest - Desolation UI

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#235]
**Describe the bug**
Desolation asks the heroes to choose if they want to "Discard Desolation." 

**What does it affect**
Card(s): Desolation
Deck(s): Blackwood Forest

**To Reproduce**
Have Desolation come into play. 

**Expected behavior**
To have the UI prompt be "have the hero discard a card?" 

**Screenshots**
![image](https://user-images.githubusercontent.com/74740837/100141123-bee1f580-2e46-11eb-9204-207e5450e6e5.png)

**Additional context**

**Comment by TopherGerkey** [comment]
#179
