### ISSUE TITLE
Quicksilver Forest of Needles

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#238]
**Describe the bug**
Forest of Needles' targeting offered a blank screen. 

**What does it affect**
Card(s): Forest of Needles
Deck(s): Quicksilver

**To Reproduce**
1. AH Stuntman, Omnitron X, Quicksilver, RA KNYFE, and Starlight against Dendron flipped. Quicksilver has Malleable Armor, Stress Hardening, and Combo Chain in play. 
2. Played Liquid Metal, ultimately ended up playing 2 Alloy Storms. 
3. Played Forest of Needles
4. Blank targeting screen. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/74740837/100145134-b987a980-2e4c-11eb-9889-b60c973f4b3c.png)

**Additional context**

**Comment by mgirman520** [comment]
Duplicates #237
