### ISSUE TITLE
Card Behavior: TheNecroCharacter, Incap 1

### ISSUE THREAD

**Issue by Vilnor** [SotMSteamMods/CauldronMods#24]
Card Text: One hero may deal himself 2 toxic damage to draw 2 cards now.

Current implementation requires targeted hero character card to TAKE damage to draw cards.  My interruption would be that as long as the damage attempt was made the cards would be drawn.  Currently redirection, prevention, damage reduction would all prevent the cards from being drawn.

Recommendation change behavior to not require damage taken.

**Comment by mgirman520** [comment]
Let's ask tosx.

**Comment by Vilnor** [comment]
Tosx confirms is just attempted damage
