### ISSUE TITLE
St Simeon's (Instruction card) 

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#244]
**Describe the bug**
The instruction card is never "flipping" and so it never goes past the turn 1 "environment cannot play cards" restriction. It just puts out a new Room every turn, while the deck sits unplayed.

This was in a game with Ambuscade, I'll test again with other villains. The deck was playing as usual in the previous update so this may relate to the latest bugfix?

**Comment by mgirman520** [comment]
This is because Character Cards are not something that environments can currently implement. So it doesn't know it should flip

**Comment by TopherGerkey** [comment]
Right, but there had previously been some workaround that was at least making the deck playable, As of today it's not playable (or rather, you can play with it, it just does nothing but swap rooms all game).
