### ISSUE TITLE
Grand Somael Card Error

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#250]
**Describe the bug**
For the power of Grand Somael, the power has a typo caused by an incomplete bold text code prior to the power starting. 

**What does it affect**
Card(s): Grand Somael
Deck(s): Malichae

**Screenshots**
![image](https://user-images.githubusercontent.com/74740837/100263806-d1ba0000-2f02-11eb-9b27-92225d04bc16.png)

**Additional context**

**Comment by breenyoung** [comment]
Stomped in another commit.  Needs reimplementation

**Comment by Vilnor** [comment]
Confirmed fixed in the current main.
