### ISSUE TITLE
Test Failure - Liquid Metal

### ISSUE THREAD

**Issue by Vilnor** [SotMSteamMods/CauldronMods#255]
**Describe the bug**
The tests TestLiquidMetalSkipCombo1Combo & The tests TestLiquidMetalSkipCombo1Finisher fail on certain seeds.
Test seems to be taking the damage and playing a combo card despite the test intent.

**To Reproduce**
Set Seed to -1937219360 and  -2016214750.

**Comment by Vilnor** [comment]
Test Name:	TestLiquidMetalSkipCombo1Finisher
Test Outcome:	Failed
Result Message:	
Expected Coalescing Spear to be in Quicksilver's hand, but it was in Quicksilver's trash
  Expected: True
  But was:  False
Result StandardOutput:	
Created game with random seed: -2016214750
========================== START GAME ==========================
DEBUG: Apostate puts "Condemnation" into play.
DEBUG: Apostate shuffles their the villain deck.
DEBUG: Went to Apostate's Start phase.
DEBUG: GameController moved Coalescing Spear from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController moved Iron Retort from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController moved Forest of Needles from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController moved Guard Breaker from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController plays Liquid Metal.
DEBUG: Revealed matching card: Guard Breaker
DEBUG: Liquid Metal moved Guard Breaker from Quicksilver's revealed cards to Quicksilver's hand.
DEBUG: Liquid Metal moves 0 cards to the top of Quicksilver's Deck.
DEBUG: Revealed card: Forest of Needles
DEBUG: Revealed card: Iron Retort
DEBUG: Revealed matching card: Coalescing Spear
DEBUG: Liquid Metal moved Coalescing Spear from Quicksilver's revealed cards to Quicksilver's hand.
DEBUG: Liquid Metal moves 2 cards to the top of Quicksilver's Deck.
DEBUG: Quicksilver shuffles their Quicksilver's deck.
DEBUG: Quicksilver initiates 2 Melee damage to Quicksilver.
DEBUG: Quicksilver deals Quicksilver 2 Melee damage.
DEBUG: Quicksilver is now at 23 HP.
DEBUG: Created decision [SelectCard/None D1 Quicksilver]
DEBUG: Liquid Metal plays Coalescing Spear.
DEBUG: Created decision [SelectTargets/None D2 Quicksilver]
DEBUG: Created decision [SelectTarget/None D2-1 Quicksilver]
MakeDecisions: [SelectTarget/SelectTarget D2-1 Quicksilver]
[Coalescing Spear] Quicksilver, Make a SelectCardDecision of type SelectTarget: [Apostate, Quicksilver, Legacy, Ra, "Condemnation"])
--- BEGIN PREVIEW ---
Selected Target: Apostate
Final Result: Quicksilver deals 3 Projectile damage to Apostate.
--- END PREVIEW ---
Selected: Apostate
DEBUG: Quicksilver initiates 3 Projectile damage to Apostate.
DEBUG: Quicksilver deals Apostate 3 Projectile damage.
DEBUG: Apostate is now at 63 HP.
DEBUG: Created decision [SelectFunction/SelectFunction D3 Quicksilver]
MakeDecisions: [SelectFunction/SelectFunction D3 Quicksilver]
Quicksilver, Make a SelectFunctionDecision: [Play a finisher, Deal yourself 2 melee damage and play a combo, Skip]
Selected: No function
DEBUG: GameController moved Coalescing Spear to Quicksilver's trash.
DEBUG: GameController moved Liquid Metal to Quicksilver's trash.

**Comment by Vilnor** [comment]
Test Name:	TestLiquidMetalSkipCombo1Combo
Test Outcome:	Failed
Result Message:	
Expected Coalescing Spear to be in Quicksilver's hand, but it was in Quicksilver's trash
  Expected: True
  But was:  False
Result StandardOutput:	
Created game with random seed: -1937219360
========================== START GAME ==========================
DEBUG: Apostate puts "Condemnation" into play.
DEBUG: Apostate shuffles their the villain deck.
DEBUG: Went to Apostate's Start phase.
DEBUG: GameController moved Forest of Needles from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController moved Iron Retort from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController moved Alloy Storm from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController moved Coalescing Spear from Quicksilver's deck to Quicksilver's deck.
DEBUG: GameController plays Liquid Metal.
DEBUG: Revealed matching card: Coalescing Spear
DEBUG: Liquid Metal moved Coalescing Spear from Quicksilver's revealed cards to Quicksilver's hand.
DEBUG: Liquid Metal moves 0 cards to the top of Quicksilver's Deck.
DEBUG: Revealed card: Alloy Storm
DEBUG: Revealed card: Iron Retort
DEBUG: Revealed matching card: Forest of Needles
DEBUG: Liquid Metal moved Forest of Needles from Quicksilver's revealed cards to Quicksilver's hand.
DEBUG: Liquid Metal moves 2 cards to the top of Quicksilver's Deck.
DEBUG: Quicksilver shuffles their Quicksilver's deck.
DEBUG: Quicksilver initiates 2 Melee damage to Quicksilver.
DEBUG: Quicksilver deals Quicksilver 2 Melee damage.
DEBUG: Quicksilver is now at 23 HP.
DEBUG: Created decision [SelectCard/None D1 Quicksilver]
DEBUG: Liquid Metal plays Coalescing Spear.
DEBUG: Created decision [SelectTargets/None D2 Quicksilver]
DEBUG: Created decision [SelectTarget/None D2-1 Quicksilver]
MakeDecisions: [SelectTarget/SelectTarget D2-1 Quicksilver]
[Coalescing Spear] Quicksilver, Make a SelectCardDecision of type SelectTarget: [Apostate, Quicksilver, Legacy, Ra, "Condemnation"])
--- BEGIN PREVIEW ---
Selected Target: Apostate
Final Result: Quicksilver deals 3 Projectile damage to Apostate.
--- END PREVIEW ---
Selected: Apostate
DEBUG: Quicksilver initiates 3 Projectile damage to Apostate.
DEBUG: Quicksilver deals Apostate 3 Projectile damage.
DEBUG: Apostate is now at 63 HP.
DEBUG: Created decision [SelectFunction/SelectFunction D3 Quicksilver]
MakeDecisions: [SelectFunction/SelectFunction D3 Quicksilver]
Quicksilver, Make a SelectFunctionDecision: [Play a finisher, Deal yourself 2 melee damage and play a combo, Skip]
Selected: No function
DEBUG: GameController moved Coalescing Spear to Quicksilver's trash.
DEBUG: GameController moved Liquid Metal to Quicksilver's trash.

**Comment by mgirman520** [comment]
This is actually working as intended. Liquid Metal is not a Combo and thus does not allow for the standard Continue Combo/Play Finisher. It instead only allows for Continuing the combo
