### ISSUE TITLE
Dendron - Mark of the Writhing Night hits hero minions

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#262]
**Describe the bug**
Dendron's Mark of the Writhing Night goes after the lowest HP hero _target_ instead of the lowest HP _hero_

**What does it affect**
Card(s): Mark of the Writhing Night
Deck(s): Dendron

**To Reproduce**
1. Fight Dendron with Unity/Captain Cosmic/Akash'Thriya/Luminary/Necro/anyone else with extra hero targets
2. Get at least one of them out
3. Have Dendron play MotWN

**Expected behavior**
MotWN should only be going after hero characters unless the damage is redirected.

**Comment by Vilnor** [comment]
Thank you for the report.  I think you have the wrong card name.  This is Ink Scar.
![image](https://user-images.githubusercontent.com/7707342/100382896-56337e00-2fea-11eb-8adc-bfdc936b7b95.png)

I'm guessing you mean Mark of the Writhing Night?
![image](https://user-images.githubusercontent.com/7707342/100382919-69dee480-2fea-11eb-8874-6cbf52eaaf6a.png)

Could you retest and update with the correct card name?  Thank you.

**Comment by LNBertolini** [comment]
Yes, it's Mark of the Writhing Night I was thinking of. I made the report after the game finished and misremembered the name.
