### ISSUE TITLE
Vanish - Abduct and Abandon with Title cards

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#277]
**Describe the bug**
Abduct and Abandon returns a card to the top of its deck. When fighting Kaargra Warfang, it places Title cards atop the villain deck.

**What does it affect**
Card(s): Abduct and Abandon
Deck(s): Vanish, Kaargra Warfang

**To Reproduce**
1. Fight Kaargra Warfang with Vanish
2. A Title card is in play from the Title deck
3. Play Abduct and Abandon, choosing the Title card
4. See that the Title card is on top of Kaargra's deck

**Expected behavior**
Title cards return to the Title deck. The card should be placed on top of the Title deck instead.

**Screenshots**

**Additional context**
Tempest's Into the Stratosphere uses `card.NativeDeck` for a similar effect.

**Comment by TopherGerkey** [comment]
Having just checked, Into the Stratosphere doesn't affect Title cards at all, so Abduct and Abandon (and Stranger's Mark of Destruction, while we're at it) shouldn't affect Title cards either.

**Comment by qoala** [comment]
Arbitrary card destruction (Fanatic's End of Days, Argent Adept's Cedistic Dissonant) still affects Title cards, iirc. They just belong to a distinct deck and match none of the hero/villain/environment labels.

These Cauldron cards should be able to affect them just fine.

**Comment by mgirman520** [comment]
This interaction is as intended.

**Comment by TopherGerkey** [comment]
Good luck with Mark of Destruction's UI!
