### ISSUE TITLE
Tiamat - Alteration play order

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#285]
**Describe the bug**
Alteration's text lists "play the top card of the environment deck" before "play the top card of the villain deck", but it plays from the villain deck first.

**What does it affect**
Card(s): Alteration
Deck(s): Tiamat

**To Reproduce**
1. Fight Tiamat
2. Tiamat plays Alteration
3. See Alteration play a Tiamat card, then play an environment card.

**Expected behavior**
The environment deck should be played first.

**Screenshots**

**Additional context**

**Comment by TheRealTails** [comment]
Just tested with more than one combo in hand - it still auto did the damage, and I was given the choice to play any of the combos.
