### ISSUE TITLE
Quicksilver Liquid Metal Auto Play

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#286]
**Describe the bug**
Quicksilver, when playing Liquid Metal, automatically dealt herself damage and played the combo in her hand. 

**What does it affect**
Card(s): Liquid Metal, Coalescing Spear
Deck(s): Quicksilver

**To Reproduce**
1. Quicksilver against Gray in Northspar.
2. 
3. Play Liquid Metal
4. Damage and combo automatically played out. 

**Expected behavior**
It's a "may" decision to deal herself damage and put the combo down. 

**Screenshots**

**Additional context**
She didn't have any other combos in her hand, so I'm not sure if it automatically is going to play the one she pulls if she has more options available to her, or if Coalescing Spear caused it. Who can say?

**Comment by mgirman520** [comment]
Duplicates #261 - Will be addressed next released
