### ISSUE TITLE
Second Waypoint Possible Bug, Possible Feature!

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#287]
**Describe the bug**
Supply Depot entered the game without Makeshift Shelter in play, so the environment got topdecked and put "What's Left of Them" into play, which then put Makeshift Shelter into play and prevented the destruction of the Supply Depot - but the Supply Depot left the environment area to attach to a hero. 

**What does it affect**
Card(s): Supply Depot, Makeshift Shelter, What's Left of Them
Deck(s): Northspar

**To Reproduce**
Described above. 

**Expected behavior**
I'm not sure what to expect. The wording of this one is odd, because it leaves open the possibility of this Power card being completely unattached and useless to heroes. But that doesn't mean it's broken. I've just never thought of this before. 

**Screenshots**

**Additional context**

**Comment by Vilnor** [comment]
Based on the text of the card,
![image](https://user-images.githubusercontent.com/7707342/102446280-6643e980-3ffb-11eb-9b6e-9731f6a074e0.png)

Supply Depot should already be destroyed before the top card is played, but the card was implemented to do the reverse.
