### ISSUE TITLE
Ram's Up Close

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#291]
**Describe the bug**
When all 5 heroes were made up close by the end of the villain turn (courtesy of Falling Meteor), none of the Up Close cards were destroyed. 

**What does it affect**
Card(s): Up Close (maybe Falling Meteor)
Deck(s): RAM

**To Reproduce**
1. Have 4 heroes be Up Close when Falling Meteor comes into play. 
2. The fifth hero gets grabbed.
3. And nothing happens. 

**Expected behavior**
For the Up Close cards to be destroyed when H of them are out. 

**Screenshots**

**Additional context**

**Comment by LNBertolini** [comment]
This is the intended behavior. The Up Closes stay out when Ram flips, the only card that gets destroyed is Fall Back. In fact Ram only flips to the front an Up Close *does* get destroyed.
