### ISSUE TITLE
The Knight - Plate Helm/Mail and Imbued Vitality

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#299]
**Describe the bug**
When Imbued Vitality leaves play, turning all the things it animated back into their normal inert selves, it also permanently takes away Plate Helm and Plate Mail's target status - even if they weren't in play when it happened!

**What does it affect**
Card(s): Plate Hem, Plate Mail, Imbued Vitality
Deck(s): The Knight, Realm of Discord

**To Reproduce**
1. Get Imbued Vitality in play
2. Destroy Imbued Vitality
3. Look through the Knight's deck for his equipment targets.

**Expected behavior**
Plate Helm and Plate Mail should revert to their normal 3HP/5HP selves

**Comment by Vilnor** [comment]
Thank you for the report.
