### ISSUE TITLE
Vanish/Starlight - Flash Recon and Wish

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#303]
**Describe the bug**
In a chain of multiple played cards, Flash Recon moved cards revealed by Wish onto the top of Starlight's deck.

**What does it affect**
Card(s):
Deck(s):

**To Reproduce**
1. Vanish and Starlight in play, Vanish has Flash Recon in hand
2. Starlight plays Wish, revealing 5 cards.
3. Wish plays Redshift from among the revealed cards.
4. Redshift allows Vanish to play Flash Recon from hand.
5. During the "reveal and replace step", see in the logs that the 4 remaining Wish-revealed cards are also replaced on top of Starlight's deck
    ```
    Revealed card: Celestial Aura
    Moving cards in Revealed location back from whence they came.
    GameController moves 5 cards to the top of Starlight's Deck.
    ```
6. Player chooses for Flash Recon to put the top card of Starlight's Deck into play.
7. See one of the Wish-revealed cards is unexpectedly played.
8. After the effect stack unwinds back to Wish, no cards remain to move to the bottom of Starlight's deck.

**Expected behavior**
Flash Recon should only have returned the 1 card it revealed (Celestial Aura) to the top of Starlight's deck.

**Screenshots**

**Additional context**

**Comment by Vilnor** [comment]
Thank you for the report!
