### ISSUE TITLE
Tiamat Mouth of the Inferno Small Image

### ISSUE THREAD

**Issue by wrhyme29** [SotMSteamMods/CauldronMods#305]
**Describe the bug**
The Mouth of the Inferno Small Image is not loading

**What does it affect**
Card(s): Tiamat: Mouth of the Inferno
Deck(s): Tiamat

**To Reproduce**
1. Load up any game with Tiamat

**Screenshots**
![20201129222311_1](https://user-images.githubusercontent.com/32969943/100568729-9bc5a480-3291-11eb-9335-0689ef43412e.jpg)

**Comment by wrhyme29** [comment]
Looking at Atlas, it looks to be left out completely

**Comment by TopherGerkey** [comment]
Confirming I have the same issue on 12/3.
