### ISSUE TITLE
Necro's Zombie Small Art

### ISSUE THREAD

**Issue by wrhyme29** [SotMSteamMods/CauldronMods#311]
**Describe the bug**
Necro's Zombie small art doesn't load (check identifier, card is NecroZombie

**What does it affect**
Card(s): Zombie
Deck(s): Necro

**To Reproduce**
1. Play Necro

**Screenshots**
![20201130002127_1](https://user-images.githubusercontent.com/32969943/100575670-375f1100-32a2-11eb-8046-4ab775f8246b.jpg)

**Comment by TopherGerkey** [comment]
Are you still seeing this? I can see Necro's Zombie smallcard art just fine.
![2020-12-03 (7)](https://user-images.githubusercontent.com/74736587/101123278-16f0c880-35ba-11eb-9387-484ec7795c13.png)

**Comment by wrhyme29** [comment]
Just checked and it looks fine now, don't know what changed. 

Closing issue
