### ISSUE TITLE
The Knight - Arm Yourself with 1 equipment in trash

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#337]
**Describe the bug**
If there's exactly 1 equipment in The Knight's trash when playing Arm Yourself, there's no effect after the equipment is selected.

**What does it affect**
Card(s): Arm Yourself
Deck(s): The Knight

**To Reproduce**
1. Have exactly 1 equipment in The Knight's trash
2. Play Arm Yourself
3. Select the 1 equipment from trash
4. No effect or log messages. The selected equipment remained in trash.

**Expected behavior**
The single card would be put into play.

Also, contrary to #189, I expected this to behave like Argent Adept's Arcane Cadence, Visionary's Foresight, etc. If there were insufficient cards for all the listed destinations, then the destinations must be used _in order_ and destinations past the available cards are ignored.

**Screenshots**

**Additional context**

I tried modifying one of the existing tests to only have a single card in trash and debugging. It looks like the stored result has `Completed=false` and ends up failing `DidSelectCards(storedResults)`. I don't understand the decision classes well enough to recognize why this is the case.

**Comment by Vilnor** [comment]
as always, thank you for the report.  Skipping the DidSelect step and just calling GetSelectedCards works.  I'll review all other uses of DidSelectCards since they will all fail in the same way if there are less choices available.

**Comment by Vilnor** [comment]
And of course a different override on the same function behaves slightly differently.
