### ISSUE TITLE
Anathema - Enhanced Senses does not damage multi-character heroes

### ISSUE THREAD

**Issue by TautvisStan** [SotMSteamMods/CauldronMods#339]
**Describe the bug**
Anathema's Enhanced Senses does not deal damage to multi-character heroes (The Sentinels)

**What does it affect**
Card(s): Enhanced Senses
Deck(s): Anathema, The Sentinels (and potential other decks with more than one hero character card)

**To Reproduce**
1. Pick Anathema as villain and The Sentinels as one of the heroes
2. Restart until Enhanced Senses is in play
3. Have The Sentinels play a card
4. No damage is dealt.

**Expected behavior**
A popup to select who to damage (or maybe all 4 of them? Can't remember the correct rules on cards like this)

**Comment by Vilnor** [comment]
The next release includes a fix for this issue, please retest at that time.
