### ISSUE TITLE
QuickSilver - Test Failure - TestLiquidMetalPlayCard

### ISSUE THREAD

**Issue by Vilnor** [SotMSteamMods/CauldronMods#342]
**Describe the bug**
TestLiquidMetalPlayCard

**What does it affect**
Card(s): LiquidMetal
Deck(s): Quicksilver

**To Reproduce**
Test fails consistently "Expected Apostate's HP to be 63, but it was 66."
Does not seem to be seed related.

**Expected behavior**
Test Should Pass

![image](https://user-images.githubusercontent.com/7707342/100787302-7182fc80-33e1-11eb-9a8c-2db4ee25d635.png)

**Comment by LNBertolini** [comment]
Oh yeah, this is related to the update that made Liquid Metal optional. I fixed it for one of the tests but not the other.
