### ISSUE TITLE
Blackwood Forest - Test Failures

### ISSUE THREAD

**Issue by Vilnor** [SotMSteamMods/CauldronMods#343]
Tracking Issue for test issues in Blackwood Forest:

Test Failures
- [x] TestDense Brambles
- [x] TestDenseBramblesThreeWayTieForLowest
- [x] TestDesolation

Ignored Tests
- [ ] TestMirrorWraithEligibleTargets_CloneAkashSeed
- [ ] TestMirrorWraithEligibleTargets_CloneProletariatClone

**Comment by LNBertolini** [comment]
The tests for Mirror Wraith are ignored for, IMO, good reason - the behavior shown in them is incorrect, but that's because the base engine doesn't accommodate the keyword-changing effects of the card.
