### ISSUE TITLE
Baccarat - Test Failure - TestBringDownTheHouseDestroy3Cards

### ISSUE THREAD

**Issue by Vilnor** [SotMSteamMods/CauldronMods#355]
Seed based test failure.

**To Reproduce**
Modify test to use seed 142903984, run test.

**Expected behavior**
Test should pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/7707342/100824651-96e52a00-3424-11eb-84b9-8d03e842cbea.png)

**Comment by Vilnor** [comment]
Test Name:	TestBringDownTheHouseDestroy3Cards
Test Outcome:	Failed
Result Message:	
Plummeting Monorail should be in Megalopolis's trash, but it was in Megalopolis's play area
  Expected: True
  But was:  False
Result StandardOutput:	
Created game with random seed: 142903984
========================== START GAME ==========================
DEBUG: Baron Blade puts Mobile Defense Platform into play.
DEBUG: Baron Blade shuffles their the villain deck.
DEBUG: Went to Baron Blade's Start phase.
DEBUG: GameController moved Cheap Trick from Baccarat's deck to Baccarat's trash.
DEBUG: GameController moved Cheap Trick from Baccarat's deck to Baccarat's trash.
DEBUG: GameController moved Ace Of Saints from Baccarat's deck to Baccarat's trash.
DEBUG: GameController moved Card Toss from Baccarat's hand to Baccarat's trash.
DEBUG: GameController moved Card Toss from Baccarat's trash to Baccarat's trash.
DEBUG: GameController moved Ace In The Hole from Baccarat's deck to Baccarat's trash.
DEBUG: GameController moved Ace In The Hole from Baccarat's deck to Baccarat's trash.
DEBUG: GameController plays Living Force Field.
DEBUG: GameController plays Plummeting Monorail.
DEBUG: GameController plays Backlash Field.
DEBUG: GameController plays Police Backup.
DEBUG: GameController plays Bring Down The House.
DEBUG: Created decision [SelectCards/None D1 Baccarat]
DEBUG: Created decision [YesNoAmount/None D2 Baccarat]
MakeDecisions: [YesNoAmount/ShuffleCardIntoDeck D2 Baccarat]
[Bring Down The House] Baccarat, Make a YesNoDecision of type ShuffleCardIntoDeck
Selected: True
DEBUG: Created decision [SelectCard/None D1-1 Baccarat]
MakeDecisions: [SelectCard/ShuffleCardIntoDeck D1-1 Baccarat]
[Bring Down The House] Baccarat, Make a SelectCardDecision of type ShuffleCardIntoDeck: [Ace In The Hole, Ace In The Hole, Cheap Trick, Cheap Trick, Skip])
WARNING: No card was specified for the test, selecting the first available choice.
Selected: Ace In The Hole
DEBUG: Created decision [SelectCard/None D3 Baccarat]
DEBUG: Bring Down The House moves 2 cards to the top of Baccarat's Deck.
DEBUG: Baccarat shuffles their Baccarat's deck.
DEBUG: Created decision [SelectCard/None D1-2 Baccarat]
MakeDecisions: [SelectCard/ShuffleCardIntoDeck D1-2 Baccarat]
[Bring Down The House] Baccarat, Make a SelectCardDecision of type ShuffleCardIntoDeck: [Cheap Trick, Cheap Trick, Skip])
WARNING: No card was specified for the test, selecting the first available choice.
Selected: Cheap Trick
DEBUG: Created decision [SelectCard/None D4 Baccarat]
DEBUG: Bring Down The House moves 2 cards to the top of Baccarat's Deck.
DEBUG: Baccarat shuffles their Baccarat's deck.
DEBUG: Bring Down The House will destroy 2 cards.
DEBUG: Created decision [SelectCards/None D5 Baccarat]
DEBUG: Created decision [YesNoAmount/None D6 Baccarat]
MakeDecisions: [YesNoAmount/DestroyCard D6 Baccarat]
[GameController] Baccarat, Make a YesNoDecision of type DestroyCard
Selected: True
DEBUG: Created decision [SelectCard/None D5-1 Baccarat]
MakeDecisions: [SelectCard/DestroyCard D5-1 Baccarat]
[Bring Down The House] Baccarat, Make a SelectCardDecision of type DestroyCard: [Living Force Field, Plummeting Monorail, Backlash Field, Police Backup, Skip])
WARNING: No card was specified for the test, selecting the first available choice.
Selected: Backlash Field
DEBUG: Bring Down The House destroys Backlash Field!
DEBUG: GameController moved Backlash Field to the villain trash.
DEBUG: Created decision [SelectCard/None D5-2 Baccarat]
MakeDecisions: [SelectCard/DestroyCard D5-2 Baccarat]
[Bring Down The House] Baccarat, Make a SelectCardDecision of type DestroyCard: [Living Force Field, Plummeting Monorail, Police Backup, Skip])
WARNING: No card was specified for the test, selecting the first available choice.
Selected: Living Force Field
DEBUG: Bring Down The House destroys Living Force Field!
DEBUG: GameController moved Living Force Field to the villain trash.
DEBUG: GameController moved Bring Down The House to Baccarat's trash.

**Comment by mgirman520** [comment]
This failure does not make sense. There are no random elements in this test. 
1. Cards are put in trash
  -All of these cards are called out by identifier and index
2. Bring Down the House is played
3. Shuffle all pairs of cards into the trash
4. Destroy corresponding number of Ongoing/Environments

**Comment by mgirman520** [comment]
This is a bug related to BaseTest ignoring indexes when pulling from hand.
This seed has all copies of Card Toss start in hand. So it moves one from the hand, then moves the same from the trash to the trash.
