### ISSUE TITLE
Knight's Arm Yourself

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#371]
**Describe the bug**
If there's only one equipment in the Knight's trash, Arm Yourself allows you to select the equipment, but nothing happens beyond that. 

**What does it affect**
Card(s): Arm Yourself
Deck(s): Knight

**To Reproduce**
1. Play Arm Yourself with one equipment in your trash. 

**Expected behavior**
The card says "up to 2" equipment cards, so I should be able to choose whether the 1 equipment card in the trash goes into my hand or into play. 

**Screenshots**

**Additional context**

**Comment by mgirman520** [comment]
Duplicates #337 - In the next release
