### ISSUE TITLE
Starlight - Promos and Redirection

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#390]
**Describe the bug**
Playing base Starlight, had Stranger's Mark of the Faded out to redirect damage and one of the options to redirect damage to is the Voidgaze Starlight from the Nightlore Council Promo

**What does it affect**
Card(s): Character cards
Deck(s): Starlight

**To Reproduce**
1. Have Stranger's Mark of the Faded out.
2. Have something deal damage to the target next to Mark of the Faded.
3. See on of the targets available to redirect to is a Starlight Promo character card.

**Expected behavior**
Promo character cards are not available as targets when they are not selected.

**Screenshots**
![starlight promo bug](https://user-images.githubusercontent.com/12156626/101081534-323ae400-3578-11eb-9360-63cc59b6b265.png)

**Additional context**
It did let me deal the damage to the promo, haven't had another redirection yet to see if the hp of the promo is being tracked.

**Comment by LNBertolini** [comment]
I can confirm that this happens, and also that it's a Mark of the Faded issue - Sky-Scraper's other sizes also show up.
