### ISSUE TITLE
Blackwood Forest - Black Tree and [deck] cards cannot be played

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#398]
**Describe the bug**
When an effect prevents villain card plays, Black Tree is able to play a villain card from beneath itself despite the card text being "play".

**What does it affect**
Card(s): Black Tree
Deck(s): Blackwood Forest

**To Reproduce**
1. Fight in Blackwood Forest
2. The Black Tree is in play with a villain card under it
3. Legacy plays Take Down, preventing villain cards from being played
4. See The Black Tree play the villain card, despite Take Down

**Expected behavior**
The Black Tree shouldn't be able to play cards from decks affected by "cannot play".

In physical form, I treat "play a random card from beneath this one" as shorthand for "shuffle the cards beneath this one then play the first one", so would expect the prevented play to result in: the card remains under The Black Tree and no cards are played from beneath it this turn.

**Screenshots**

**Additional context**
Vanilla precedent for skipping The Black Tree's end-of-turn play, though I could see an argument where the Cauldron-specific wording "play a random card" could require that only playable cards be randomized.

> If hero cards cannot be played, then a Primordial Seed on top of the environment deck would not be played on the environment turn, effectively nullifying the card play of the environment turn that turn. If environment cards cannot be played, that does not prevent the play of a primordial seed card from the top of the environment deck.

https://greaterthangames.com/comment/204002#comment-204002

**Comment by Vilnor** [comment]
Agree, notes for solution
Card should still be randomly choose based on the general SoTm rule of 'try to do the thing' and let it fail.
Card needs to be checked with GameController.CanCardBePlayed and if not, disable a message and end the trigger
I think the person playing the card should be the ownerTurnTaker, but the enviroment.
