### ISSUE TITLE
Blackwood Forest - Black Tree face down cards and deck inspection

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#399]
**Describe the bug**
It is possible to infer what cards are beneath The Black Tree by inspecting the deck contents.

**What does it affect**
Card(s): The Black Tree
Deck(s): Blackwood Forest

**To Reproduce**
1. Fight in Blackwood Forest
2. Environment plays The Black Tree, taking face down cards from each hero and the villain
3. Click on villain or hero deck to view cards in that location and compare its contents with the deck list
4. Infer the cards under The Black Tree by process of elimination. Maybe get lucky and an obvious unique card (like Ezael) is suddenly missing.

**Expected behavior**
Inspecting deck contents includes face down cards that were moved out without a reveal. Preferably with a warning that the deck contents may not be accurate.

Same behavior as when Santa Guise hands out presents. With or without Guise giving the warning.

**Screenshots**

**Additional context**

It's possible this is a special case that we'd depend on Handelabra making available to mods.
I didn't spot any obvious flags being set by Santa Guise' implementation, so there may be a special case checking for him elsewhere in the code.

**Comment by Vilnor** [comment]
Comparing to Chokepoint (who also steals cards) she implemented the orverride of AskIfCardIsVisibleToCardSource which seems to make her facedown area cards non-visible.  This might be part of a solution in St Simeon's as well.

**Comment by breenyoung** [comment]
I've implemented the AskIfCardIsVisibleToCardSource as @Vilnor suggested and now you can longer see what exact cards are beneath The Black Tree.  Inferring what card may be under there is still possible for a resourceful player by carefully inspecting their deck.
