### ISSUE TITLE
v0.2.1 - Quicksilver - Liquid Metal - Use Better YesNoDecision for display.

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#420]
**Describe the bug**
The current YesNoDecision doesn't explain much for Liquid Metal. It is better to use the DealDamageSelf selection type, which has a message attached. (A yesNoAmountDecision may also work better than the current YesNoDecision.) 

**What does it affect**
Card(s): Liquid Metal
Deck(s): Quicksilver

**To Reproduce**
Play Liquid Metal and confirm the YesNoDecision displays as "Yes or No?"

**Expected behavior**
A Clearer Message.

**Comment by TheLastTrueBlade** [comment]
Does it look like this?

![20201205204617_1](https://user-images.githubusercontent.com/75555294/101271791-ef753980-373a-11eb-8a4f-0afe72febeca.jpg)

At first I was confused because it asked in I wanted to play Liquid Metal...when I had already done so.

**Comment by Ruduen** [comment]
I think the reveals are a smaller problem because the new cards go into your hand, though it's noted that the card's wording is already awkward, since 'reveal until you reveal a X and a Y' is awkward because of scenarios where you can reveal two of X before you reveal a Y, and then it becomes ambiguous which X can qualify as a revealed one. But that's a card wording issue with the base card, not the implementation. 

But while I forget what the exact image is, yes, your screenshot would be a problematic example.
