### ISSUE TITLE
Titan - Stubborn Goliath redirect is not optional

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#445]
**Describe the bug**
The applied redirection effect currently appears to be mandatory.

**What does it affect**
Card(s): Stubborn Goliath
Deck(s): Titan

**To Reproduce**
1. Have Titan
2. Play Stubborn Goliath
3. Use its power on the villain
4. When the villain attempts to deal damage, see that it is redirected to Titan without a choice.

**Expected behavior**
Should be offered a y/n "do you want to redirect", as the card says "you _may_ redirect that damage to Titan" (emphasis added)

**Screenshots**

**Additional context**

**Comment by mgirman520** [comment]
The RedirectDamageStatusEffect IsOptional attribute, does not make it optional

**Comment by LNBertolini** [comment]
I can do this with an OnDealDamageStatusEffect

(love those "optional" parameters that don't do anything...)

**Comment by qoala** [comment]
I had an issue with OnDealDamageStatusEffect not supporting the flag to block execution if it needed to ask the player for a choice (in the Starlight incap fix), so this might be even messier.

**Comment by LNBertolini** [comment]
I just gave AllowFastCoroutinesDuringPretend a getter to check whether there are any active status effects from Stubborn Goliath. Should work, I expect. I'll push the changes up and give it a quick in-game playtest.
