### ISSUE TITLE
Swarmeater - Seed Test Failure - TestNonCharacterCardHeroCantMoveSingleMindedPursuit

### ISSUE THREAD

**Issue by Vilnor** [SotMSteamMods/CauldronMods#460]
Seed based test failure

Created game with random seed: -1342227959

**Comment by Vilnor** [comment]
Test Name:	TestNonCharacterCardHeroCantMoveSingleMindedPursuit
Test Outcome:	Failed
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
Result StandardOutput:	
Created game with random seed: -1342227959
DEBUG: GameController moved Stalker Aug from the villain deck to the villain deck.
DEBUG: GameController moved Fire Aug from the villain deck to the villain deck.
DEBUG: Applying ongoing effect: Swarm Eater cannot deal damage 1 more time.
Message: Swarm Eater cannot deal damage 1 more time. [ Swarm Eater ]

**Comment by mgirman520** [comment]
Swift Bot was in hand and would not get played. Switched to Cpt Cosmic/Cosmic Crest
