### ISSUE TITLE
v0.2.2 - Swarm Eater - Insatiable Charge - Incorrect Destruction Timing

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#470]
**Describe the bug**
Right now, Swarm Eater deals damage, and destroys Ongoings/Equipments upon dealing damage. However, based on its wording, I believe it is supposed to finish dealing damage, and then destroy everything after damage has completed. 

(This is since it is worded as "For Each", indicating the action should occur as a lump action afterwards, using Omnitron's Technological Singularity as the source. If the intent was for destruction to be immediate, the wording should state "When/Whenever a target is destroyed...) 

**What does it affect**
Card(s): Insatiable Charge
Deck(s): Swarm Eater

**To Reproduce**
1. Have multiple targets for Swarm Eater to destroy. 
2. Start having Insatiable Charge destroying targets.

**Comment by mgirman520** [comment]
tosx confirmed blow up as you go 
![image](https://user-images.githubusercontent.com/21280903/105636457-7b037080-5e36-11eb-972b-2a72a4477f8e.png)
