### ISSUE TITLE
Fire Aug Absorbed is too powerful - and then it wicked wasn't.

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#483]
**Describe the bug**
When Fire Aug was considered absorbed under Swarm Eater, I think it forced all players to discard a card for it's start of turn effect - I however, can't confirm because I rewound and suddenly the Fire Aug didn't do anything. 

**What does it affect**
Card(s): Fire Aug
Deck(s): Swarm Eater

**To Reproduce**
1. Have Fire Aug absorbed.

**Expected behavior**
It should be H-2 heroes, I believe, who should be forced to discard a card, not all of them. In a Five Hero game the card said only 3 needed to discard, and the UI should ideally just go away once enough heroes were chosen, right? I can't confirm what exactly happened, however, because the Aug just stopped working once I rewound. 

**Screenshots**

**Additional context**

**Comment by Vilnor** [comment]
Thank you for the report.  Great work.
