### ISSUE TITLE
Cypher - Extra Play Augment doesn't grant play if played during play phase.

### ISSUE THREAD

**Issue by Vilnor** [SotMSteamMods/CauldronMods#501]
**Describe the bug**
If you play Retinal Aug during Cypher's play phase it should grant an additional Play Card action immedately like HUD Googles.

**What does it affect**
Card(s): Retinal Aug, Fusion Aug
Deck(s): Cyphers

![image](https://user-images.githubusercontent.com/7707342/101993277-40c78080-3c87-11eb-901e-9ae381c6f15e.png)

No extra play
![image](https://user-images.githubusercontent.com/7707342/101993288-52a92380-3c87-11eb-9370-478d031b64a7.png)

**Comment by qoala** [comment]
Relatedly, it should also grant an extra play if it is moved to the currently active hero during their play phase.

I'm not sure if losing HUD Goggles in response to your first play results in being unable to play a 2nd card. If so, similar behavior should occur if moved away from the currently active hero.

**Comment by Vilnor** [comment]
Good points.
