### ISSUE TITLE
Vector - Undiagnosed Subject, revealed card UI

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#507]
**Describe the bug**
When asking the player whether or not to discard or replace the revealed card, is it possible to display the revealed card to the right of the choice (where an affected target is displayed for some choices)?

**What does it affect**
Card(s): Undiagnosed Subject
Deck(s): Vector

**To Reproduce**
1. Fight Vector
2. Villain plays Undiagnosed Subject
3. Destroy Undiagnosed Subject
4. See "Undiagnosed Subject revealed Blood Sample" (or other card)
5. Be offered a choice between "discard card" or "replace card", but have already forgotten which card was revealed.

**Expected behavior**
In the choice UI, Blood Sample already appears on the left of the choice, as the source of the effect. The revealed card should appear on the right of the choice, as the target of the effect.

**Screenshots**

**Additional context**

**Comment by wrhyme29** [comment]
![20201212234504_1](https://user-images.githubusercontent.com/32969943/102004199-25cf2d80-3cd4-11eb-8564-8738ba149f04.jpg)

This will be in the next fix
