### ISSUE TITLE
Mara - Smoke and Mirrors, multiple in play

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#515]
**Describe the bug**
With multiple copies of Smoke and Mirrors in play, it's possible to destroy one of them and fail to prevent the damage

**What does it affect**
Card(s): Smoke and Mirrors
Deck(s): Magnificent Mara

**To Reproduce**
1. Magnificent Mara has 2 copies of Smoke and Mirrors in play
2. Initiate damage to a hero target
3. "Which card should take effect first" between the Smoke and Mirrors. Choose either.
4. "Do you want to prevent the damage?". Choose Yes.
5. See Smoke and Mirrors is destroyed
6. "Do you want to prevent the damage?" (from the other Smoke and Mirrors) Choose No.
7. See the damage occur normally

Alternatively,
3. (either)
4. (yes)
6. (yes)
7. See both copies of Smoke and Mirrors destroyed. The damage is prevented.

Alternatively,
3. (either)
4. (no) This copy is not destroyed
6. (yes) This copy _is_ destroyed
7. "Do you want to prevent the damage?" (from _a_ Smoke and Mirrors. Not sure which one) Choose No.
8. One copy is destroyed. The damage is prevented.

**Expected behavior**
After preventing damage with one copy of Smoke and Mirrors, damage execution stops and can't accidentally deal the damage anyways.

It is not possible to destroy both copies of Smoke and Mirrors on the same damage instance.

**Screenshots**

**Additional context**

**Comment by LNBertolini** [comment]
This doesn't seem to be happening in the automated tests. It's possible that it's to do with an interaction with the UI, I'll see if I can replicate it.

**Comment by LNBertolini** [comment]
I can confirm that this does happen in-game! I'll see if I can figure anything out.
