### ISSUE TITLE
Starlight - Nightlore Council variant, draw order

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#536]
**Describe the bug**
Draw order appears to be inverted. Starlight of Cryos-4 is in front, blocking poor Starlight of Terra.

**What does it affect**
Card(s): Nightlore Council variant
Deck(s): Starlight

**To Reproduce**
1. Start a game with Starlight (Nightlore Council)
2. See Starlight of Terra almost completely hidden by Starlight of Cryos-4

**Expected behavior**
Starlight of Cryos-4 is in the back. It feels likely that order is completely reversed, but in the current state it's not clear whether or not Terra and Asheron are in the correct order relative to each other.

**Screenshots**
![cauldronmod_20201213_starlightcouncil](https://user-images.githubusercontent.com/512290/102052646-38606a00-3d9b-11eb-9e52-4acc930e9aed.jpg)

**Additional context**
Locally built at 7c71c3b1ac (2 commits ahead of v0.2.4) and manually copying over the art folders. In case that might be relevant to art assets.

**Comment by Vilnor** [comment]
The reordering of the Starlights in the decklist made in pull 561 should fix this, please retest.

**Comment by qoala** [comment]
Confirmed fixed.
