### ISSUE TITLE
Special Strings for Targeting

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#538]
**Describe the bug**
Many cards, specifically villain and environment cards, that deal damage to targets based on who has the highest health, who has the most ongoings, etc., don't tell the player who that target currently is. 

**Expected behavior**
It would be nice to get those special strings. 

**Screenshots**

**Additional context**

**Comment by Vilnor** [comment]
Thank you for the report.  It would be helpful to have specific examples of cards that need this information.

**Comment by wrhyme29** [comment]
I'm going through all villains and environments and adding these in.

**Comment by wrhyme29** [comment]
Special Strings are in for base set and experimental villains
