### ISSUE TITLE
St. Simeon's Catacombs - Never able to play cards

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#544]
**Describe the bug**
St. Simeon's Catacombs initially prevents itself from playing cards. However it never removes this effect.

(I remember this working before. Not sure when it stopped working)

**What does it affect**
Card(s): Instruction cards
Deck(s): St. Simeon's Catacombs

**To Reproduce**
1. Start a game in St. Simeon's Catacombs.
2. See the instruction card already in play at the start of the game (like other character cards)
3. See the room container card enter play during start of game resolution. "the environment cannot play cards" message appears.
4. At the end of the environment turns, see a room enter play.
5. See further room behavior work correctly (can destroy at end of environment turn, rooms are replaced, etc)
6. Never see "the environment cannot play cards" status effect removed.

**Expected behavior**
The environment begins playing non-Room cards after the first round.

**Screenshots**

**Additional context**

It feels like the instruction card isn't triggering its `Play()` method, where it should be attaching the status effect to a `_sideStatusEffects` list to be cleared on flip. This apparently doesn't match what happens in the tests.

**Comment by wrhyme29** [comment]
I tested this out, and Catacombs was behaved normally. Can others try this out and see if they experience the same issue?

**Comment by wrhyme29** [comment]
I figured this out - it was a reloading issue so if you had reloaded the game or undo'd in game before the flip to the back, it lost track of the cannotPlayCards effect and couldn't remove it later. I reimplemented entirely which has resolved the issue
