### ISSUE TITLE
Starlight (Nightlore Council variant) - large and small character card art 

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#565]
**Describe the bug**
The Starlight character cards have incomplete logos. They are labeled simply "of Terra," "of Asheron," and "of Cryos-4."

**What does it affect**
Card(s): Both large and small versions of the character cards.
Deck(s):

**Expected behavior**
The cards's logos should have "Nightlore Council" at the top, then "Starlight," then the individual identifiers.

**Screenshots**
![2020-12-19](https://user-images.githubusercontent.com/74736587/102694028-15dbb000-41e4-11eb-9049-6aa06ff0abc1.png)
![2020-12-19 (1)](https://user-images.githubusercontent.com/74736587/102694038-1e33eb00-41e4-11eb-8f0b-b8f918055591.png)
![2020-12-19 (2)](https://user-images.githubusercontent.com/74736587/102694042-2429cc00-41e4-11eb-87e4-8f13bd1da26e.png)
![2020-12-19 (3)](https://user-images.githubusercontent.com/74736587/102694046-2c820700-41e4-11eb-9b67-d4f43fb1c33f.png)

Compare to the images from the physical cards:
![Promo_Starlight - Nightlore Terra](https://user-images.githubusercontent.com/74736587/102694080-5d623c00-41e4-11eb-927a-5486e49939d0.png)
![Promo_Starlight - Nightlore Cryo](https://user-images.githubusercontent.com/74736587/102694083-5fc49600-41e4-11eb-8967-e56655337787.png)
![Promo_Starlight - Nightlore Asheron](https://user-images.githubusercontent.com/74736587/102694084-618e5980-41e4-11eb-87df-49d263a887f7.png)

**Comment by MSpekkio** [comment]
Would it be possible to do something nicer for the Instruction card?  Without the text on the instruction card, the small card art looks out of place.

![image](https://user-images.githubusercontent.com/7707342/103188850-1e914d80-4898-11eb-98ff-7c7c42dd3a7f.png)
