### ISSUE TITLE
v0.2.4 - The Cricket - Sonic Amplifier - Yes/No indicates Sonic Amplifier Rather Than Target Card

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#586]
**Describe the bug**
Sonic Amplifier's Yes/No text asks whether or not you want to put Sonic Amplifier beneath Sonic Amplifier, rather than indicating the top card of a deck. (I'm not sure of the correct yes/no to use, but even the generic form or '1 card' would be more appropriate than the current text, which is strictly incorrect.) 

**What does it affect**
Card(s): Sonic Amplifier
Deck(s): The Cricket

**Screenshots**
![20201221201309_1](https://user-images.githubusercontent.com/45407351/102840725-1d0fe300-43c9-11eb-8fee-c8c9e9bc20d1.jpg)

**Comment by MSpekkio** [comment]
Fixed, thank you for the report.
![image](https://user-images.githubusercontent.com/7707342/103174989-aba2bb00-4834-11eb-8393-7b9085ba7452.png)

**Comment by LNBertolini** [comment]
That's worse! You're not supposed to be able to tell what the card you're about to put under Sonic Amplifier is unless you've already seen it some other way. Now you're not just storing up damage for a big punch, you're also getting to filter your deck.

**Comment by Ruduen** [comment]
This appears to be back to the original problematic form. Rather than use Sonic Amp as an associated card, I believe the correct option is to just use the related decision to indicate one card is being moved - that at least gets closer.
