### ISSUE TITLE
Pyre - Initial Framework Implementation

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#594]
NOTE: This is not a bug. (Bug Report is just the only available issue type.) 

Attached are some preliminary implementations for Pyre's core mechanic. Some of it is ToDo code, but I wanted to test and confirm if things could be done via the keyword. So far, the core character card's power is functioning, and I used Chromodynamics to test the effects from a non-character card. 

Unit tests have appropriately been created and confirmed as functional. Note that I did not try to create items for the full card list - my tests involved removing any other cards from the card list (and adding more copies of Chromodynamics). 

Note that this implementation links relevant triggers to Pyre to remove keywords. The alternative would be to add a number of status effects that last until the card is removed altogether, which could result in odd effects. 

[PyrePrototype.zip](https://github.com/SotMSteamMods/CauldronMods/files/5738351/PyrePrototype.zip)

**Comment by wrhyme29** [comment]
Thanks for the work on this! We ended up a going a different route (putting fake irradiated cards next to appropriate cards in the hand) due to interactions with existing keyword cards.
