### ISSUE TITLE
Phase - Special/Status text for removed obstacles

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#604]
**Describe the bug**
There's no UI reminder of obstacles removed from the game by Phase's character card

**What does it affect**
Card(s): Phase
Deck(s): Phase

**To Reproduce**
1. Fight vs Phase
2. Allow Phase to flip and remove an obstacle from the game
3. See no reminder or indication of the removed obstacles until Phase attempts to deal damage (where the +X appears in the damage calculation)

**Expected behavior**
Both:
1) Special text listing the number of obstacles removed from the game (for the damage buff) when inspecting Phase's character card.
  * This one might be expected immediately at the start of game with "There are no/0 obstacles removed from the game"
2) Status text in the lightning menu listing "Cards removed from game: Precarious Rubble, etc" (similar to the text that appears from Deadline, Setting Sun Ra, and similar effects)

**Screenshots**

**Logs**

**Additional context**

**Comment by MSpekkio** [comment]
![image](https://user-images.githubusercontent.com/7707342/103234765-779bc880-490e-11eb-9ab4-c173bcda7a3e.png)
