### ISSUE TITLE
Phase - Residual Desynchronization when target is destroyed

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#605]
**Describe the bug**
When a hero deals damage that destroys an obstacle, Residual Desynchronization attempts to deal damage from the destroyed obstacle and fizzles.

**What does it affect**
Card(s): Residual Desynchronization
Deck(s): Phase

**To Reproduce**
1. Phase has Residual Desynchronization and an obstacle (e.g. Precarious Rubble) in play
2. A hero deals enough damage to destroy the obstacle
3. See Residual Desyncronization initiate damage from the destroyed obstacle, including the damage preview opening
4. See the damage fizzle

**Expected behavior**
Residual Desynchronization doesn't attempt damage if the target is destroyed.

**Screenshots**

**Logs**

**Additional context**

**Comment by MSpekkio** [comment]
Tested this and discussed with the group and confirmed that the damage fizzle is correct behavior and consistant with the base game.  I've added a test to document the behavior, and set the counter flag on the trigger so you get the standard "Residual Desynchronization reacts" message.
