### ISSUE TITLE
Phase - Density Regulator, tied lowest HP

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#606]
**Describe the bug**
When hero targets are tied for the lowest HP, then all hero targets are dealt damage, despite "each hero target except the hero target with the lowest HP"

**What does it affect**
Card(s): Density Regulator
Deck(s): Phase

**To Reproduce**
1. Have 2 hero targets tied for the lowest HP
2. Phase plays Density Regulator
3. At the end of the villain turn, see Density Regulator ask for damage order with all hero targets listed. All hero targets are dealt damage.

**Expected behavior**
A choice "Which hero target is considered to have the lowest HP" between the tied heroes. After that choice is made, then a damage order choice for all other hero targets is started.

**Screenshots**

**Logs**

**Additional context**

**Comment by MSpekkio** [comment]
implementation wasn't excluding lowested in any way.  Test was missing as well. thank you.
