### ISSUE TITLE
Superstorm - Ride the Currents, display bug

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#608]
**Describe the bug**
When moving an environment card at the start of the villain turn, the card move is not visually displayed until the UI switches to the hero turns (presumably when it forces an update of some sort)

**What does it affect**
Card(s): Ride the Currents
Deck(s): Superstorm

**To Reproduce**
1. Superstorm Akela has multiple cards in play, including Ride the Currents
2. At the start of the villain turn, specify a new position for one of the environment cards
3. See no change in the displayed environment play area
4. After the UI switches panel positions to a hero turn, see the environment cards are now in the modified order

**Expected behavior**
The order change is visible immediately.

**Screenshots**

**Logs**

**Additional context**

**Comment by wrhyme29** [comment]
This is an engine limitation in its current form - we have no way to force the UI to update. Its worth exploring other ways to implement the effect to see if that can trigger the UI, but otherwise thats just going to be how it is
