### ISSUE TITLE
v0.2.4 - Halberd Experimental Research Center - Halberd-O3: Prophet

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#619]
**Describe the bug**
Prophet's ability indicates that each player may look at the top card of their deck and put it at the top or bottom. However, if there is not test specifying "in turn order", this effect should allow players to determine the order in which they act. There are a few niche cases where ordering can matter (such as if an unusual card has been stacked on top of the deck, or a custom card takes effect when revealed the same way some of Oblivaeon's cards do). Similarly, since it says "may", the reveal should not be mandatory, and should be skippable. (This can otherwise interact inappropriately with Shinobi Assassin.) 

Currently, it automatically goes in turn order and is mandatory, rather than allowing player choice and being optional.

**What does it affect**
Card(s): Halberd-O3: Prophet
Deck(s): Halberd Experimental Research Center

**Comment by qoala** [comment]
Preferable UI would be the series of choices listing all players that haven't gone yet + skip. So that player's don't need to also pick yes/no for revealing cards.

**Comment by MSpekkio** [comment]
Updated UI to have the select player, skip, auto dialog per suggestion.  This kind of feedback is very helpful as most of the dev team testing is automated.
