### ISSUE TITLE
Swarm Eater - Pursued hero may move next to a destroyed target

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#630]
**Describe the bug**
> Whenever a pursued hero deals damage to a target other than Swarm Eater, you may move single-minded pursuit next to that target.

If the pursued hero destroys a target via damage, the player has the option to move Single-Minded Pursuit next to the destroyed target.

**What does it affect**
Card(s): Swarm Eater "Power Hungry" side, Single-Minded Pursuit
Deck(s): Swarm Eater

**To Reproduce**
1. Swarm Eater has Single-Minded Pursuit in play next to a hero.
2. There is a low HP non-character target (not sure how this behaves if you incap a hero with damage)
3. The pursued hero deals sufficient damage to the target to destroy it.
4. Swarm Eater offers to move Single-Minded Pursuit. Choose yes.
5. See Single-Minded Pursuit next to the destroyed card in the appropriate trash.

**Expected behavior**
Either the option to move Single-Minded Pursuit shouldn't have been given, or because the pursued target left play then Single-Minded Pursuit should've been destroyed.

**Screenshots**

**Logs**

**Additional context**
built at ed4989b0cdec

**Comment by MSpekkio** [comment]
Definitely a edge case, but I've made the judgement call that "targets" in the text must mean InPlay Targets, and excluded a destroyed card from getting the pursuit.
