### ISSUE TITLE
Impact - Gravitic Orb, multiple copies

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#631]
**Describe the bug**
Multiple copies of Gravitic Orb next to the same target are all destroyed to prevent a single damage instance.

**What does it affect**
Card(s): Gravitic Orb
Deck(s): Impact

**To Reproduce**
1. Impact plays Gravitic Orb next to the villain
2. Impact plays another Gravitic Orb next to the villain
3. The villain attempts to deal damage
4. "which card should take effect first" between the 2 orbs. Choose either.
5. See one gravitic orb destroyed.
6. See the damage calculation show the damage was prevented.
7. See the other gravitic orb also get destroyed.

**Expected behavior**
Only 1 Gravitic Orb is destroyed to prevent damage. Additional orbs remain in play to prevent subsequent damage attempts.

Compare Skyscraper's Rebounding Debilitator.

**Screenshots**

**Logs**
```
Went from Ambuscade's PlayCard phase to End phase.
Created decision [SelectCard/None D195]
Created decision [SelectCard/None D Impact]
Created decision [SelectTargets/None D196]
Created decision [SelectTarget/None D196-1]
Ambuscade initiates 3 Projectile damage to Freedom Six Tachyon.
Created decision [SelectCard/None D197 Impact]
Created decision [SelectCard/None D Impact]
Gravitic Orb destroys itself!
GameController moved Gravitic Orb to Impact's trash.
DealDamageAction of Ambuscade was prevented by Gravitic Orb.
Gravitic Orb destroys itself!
GameController moved Gravitic Orb to Impact's trash.
```

**Additional context**
Built at ed4989b0cdec

**Comment by MSpekkio** [comment]
Thank you quola, this is another I can't replicate in a test mode.  I made a change to line our code up with Skyscraper's.  If possible, please try and retest in game.

**Comment by qoala** [comment]
Built at 8a636e15 on misc-issues-12-28, issue is still present.

My in-game repro uses the following set up:
F6 Tachyon, Renegade Impact, XPW Fanatic, Greatest Legacy v Ambuscade at Insula Primalis
Repeatedly using F6 Tachyon's innate to rapidly draw towards Gravitic Orbs, then Renegade Impact's innate to get both in play simultaneously (as long as another ongoing had been played ahead of time).

**Comment by MSpekkio** [comment]
Thank you sir.

**Comment by qoala** [comment]
Figured it out. Replace `if (IsRealAction())` with `if (IsRealAction(dd))` @MSpekkio 

This change fixes the issue when I run it in the client (off of the same commit as my last comment)

**Comment by MSpekkio** [comment]
You rock. I'll post that to the branch now.

**Comment by MSpekkio** [comment]
Mara's Smoke and Mirrors has the exact same pattern, I applied the same change (`IsRealAction() => IsRealAction(dda)`) there as well.
