### ISSUE TITLE
Mark of Quickening

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#636]
**Describe the bug**
When playing Mark of Quickening on the Stranger (during the SqueakyNote stream), it did not allow a second play phase.

**What does it affect**
Card(s): Mark of Quickening
Deck(s): The Stranger

**To Reproduce**
Dendron vs. Sranger, Sorrows Baccarat, and Chaos Necro
I wasn't the one playing but we did notice that when Mark of Quickening was played during the play phase on the Stranger, it didn't allow a second play. 

**Expected behavior**
It should have allowed a second play, a la Tachyon playing her HUD goggles. 

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by MSpekkio** [comment]
Issue was previously reported in #607, and is fixed in next release.  thank you.
