### ISSUE TITLE
v0.2.4 - Necro - Undead Cards - HP Display is Non-Obvious

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#640]
**Describe the bug**
Necro's Undead should generally have their HP set to the number of rituals in play plus 2. However, this is represented by a "#", which is not displayed - instead, it should display the "#". (Note that this does not match S-84 Automaton Drone, which uses a "*" to indicate variable maximum HP - however, that is a consistency issue with the printed card, and may not be as appropriate to fix.) Note that this is apparently done with the "hitpointsText" item in the DeckList. 

**What does it affect**
Card(s): Undead Cards
Deck(s): Necro

**Expected behavior**
Display "#" for HP under standard circumstances. (A consistency pass would change this to "*", but that would be inconsistent with the actual card, so that would be up to deck designer discresion.) 

**Screenshots**
![20201229014126_1](https://user-images.githubusercontent.com/45407351/103267730-cdf12180-4977-11eb-8bbc-2e2f00d5c405.jpg)

**Comment by MSpekkio** [comment]
Unfortunately, this is a engine limitation.  We've reported the issue to the dev team.  Long term if no solution is found the undead could be recoded to to not be targets until they enter play with the result that the '2' would be hidden.  I tested a solution where hand/deck undead had there HP continueally updated as Ritual's left/entered play but it was very slow.
Sorry.
