### ISSUE TITLE
Cricket - Wasteland Ronin incap UI for card with multiple powers

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#641]
**Describe the bug**
> Select a power on a card in play. The next time a hero uses it, they may immediately use it again.

When selecting a power on a card with multiple powers (Titan's Chaplain, Santa Guise, etc), the UI is non-intuitive.

**What does it affect**
Card(s):
Deck(s):

**To Reproduce**
1. Wasteland Ronin Cricket is incapped
2. Titan has Chaplain in play
3. Cricket uses the 2nd incap ability
4. Choose Chaplain
5. See "Cricket, Pick a number: 0, 1". Wonder what is going on.
6. Pick 0, to select the first power.

**Expected behavior**
"First Power" and "Second Power" in a choice list (consistent with the "Use First Power"/"Use Second Power" buttons when examining such a card during a choose-and-use-power action).
I don't know whether or not the client and engine support more than 2 powers, if so, it presumably keeps using ordinal words.

Also display the chosen card to the right of this choice as a related card.

**Screenshots**
![cauldron-20201228-cricketincap](https://user-images.githubusercontent.com/512290/103267880-a76ebe80-4956-11eb-86df-0cc4d90b365f.jpg)

**Logs**

**Additional context**
Built at 0a3dbef02df7

**Comment by MSpekkio** [comment]
So this is a interesting case.  This power will also fail to work with Granted Powers such as Cosmic Weapon.

**Comment by MSpekkio** [comment]
And 8 hours later a version that supports Cosmic Weapon and multi power cards is now working.  Thanks incap powers.
