### ISSUE TITLE
Celadroch - Lord of the Midnight Revel retaliation fires on 0 damage

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#642]
**Describe the bug**
> The first time another villain target would be dealt damage each turn, this card deals the source of that damage H melee damage
Trigger fires even if damage was reduced to zero.

**What does it affect**
Card(s): Lord of the Midnight Revel
Deck(s): Celadroch

**To Reproduce**
1. Celadroch has Lord of the Midnight Revel in play
2. Celadroch plays Gallows Blast (or there otherwise exists damage reduction)
3. Initiate low damage to Celadroch, reduced to 0
4. See Lord of the Midnight Revel retaliate

**Expected behavior**
Retaliation damage is only triggered when damage is actually dealt.

Separately, this card uses "would be dealt", but not "first" (contrast with Dendron's Blood Thorn Aura). Is this supposed to be pre-taliation damage?

**Screenshots**

**Logs**

**Additional context**
Built at 0a3dbef02df7

**Comment by MSpekkio** [comment]
The pre-taliation damage question is a good one as my first thought was 'yes it's supposed to be pre damage', but that certainly isn't what I coded him to do 😄.  I'll check with the channel.  Changing the trigger to before will likely expose edge cases like Lady of the Wood's Thundershawl Cape so might be a net loss.

**Comment by MSpekkio** [comment]
Tosx confirmed the timing is correct, and I've added a Amount > 0 check to the trigger.  As always thank you for the detailed testing.
