### ISSUE TITLE
Tango One 1929 Base Power

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#644]
**Describe the bug**
Tango One's Base Power didn't activate at the start of her turn, despite the Special String being present in the Effects list that said it would. 

**What does it affect**
Card(s): Tango One 1929
Deck(s): Tango One

**To Reproduce**
I don't know what happened - it was working just fine before. It may be because I exited the game and reloaded it in between her turns - it's the only reason I can think of, as her power was working just fine before I did that. 

**Expected behavior**
The power to go off. 

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by wrhyme29** [comment]
I made a test specifically for this situation, where I save and load before her next turn, but it always goes off without an issue
