### ISSUE TITLE
Malichae Djinn Powers

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#645]
**Describe the bug**
With the new update, Djinn Powers are doing their old problem of not showing up on the screen when clicked.

**What does it affect**
Card(s): Djinn Power Cards
Deck(s): Malichae

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**
To read the power. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74740837/103322176-003f6500-49f2-11eb-9776-b43cd0c032b8.png)

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by MSpekkio** [comment]
Thank you for the report, looks like this got broke we I added MSS Malichae.  Annoying that the automated tests work both before and after re-fixing this without change.
