### ISSUE TITLE
Titan's Combat Pragmatism

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#646]
**Describe the bug**
Destroying Titan's CP allows me to use a power on him - but it went because of an ongoing destruction card, not because a non-hero target entered play. 

**What does it affect**
Card(s): Combat Pragmatism
Deck(s): Titan

**To Reproduce**
1. Put CP in play.
2. Akash Bhuta plays Earth's Sacrifice.
3. Have CP be one of the Ongoings be destroyed by the card.

**Expected behavior**
It should only allow a power because a non-hero card entered play, not because it was destroyed by a non-hero destruction card. 

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by MSpekkio** [comment]
Bug, card's use power effect will incorrectly trigger whenever Combat Pragmatism is destroyed.
