### ISSUE TITLE
Tiamat - Elemental Frenzy

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#65]
Pulled an elemental card from the trash and put it under this ongoing as intended, but also caused the environment deck to play a card.

**Comment by mgirman520** [comment]
When the card is destroyed it plays the top card of the Villain deck, what I'm assuming happened is that it played Alteration which plays the top card of the environment deck and the top card of the villain deck.

**Comment by TopherGerkey** [comment]
Elemental Frenzy was played and pulled in two "Element of Ice" cards from the trash. One of those was played at the end of the villain turn, leaving Elemental Frenzy intact with one card under it, then an environment card got played. 

Sorry, being much more specific in more recent bug reports!

**Comment by mgirman520** [comment]
If you still have the log, that would be useful, but I'm assuming its long gone

**Comment by TopherGerkey** [comment]
I'm afraid so. I have tested several more times and not been able to replicate this one myself.

**Comment by mgirman520** [comment]
Closing until this can be replicated.
