### ISSUE TITLE
Catacombs Loading Issues

### ISSUE THREAD

**Issue by wrhyme29** [SotMSteamMods/CauldronMods#66]
Instructions card is blank, does not start with all the rooms under it
It allows for playing the top card of the environment deck on the first turn instead of playing a room

**Comment by TopherGerkey** [comment]
Additionally end-of-turn effects from this deck's targets are not activating.

**Comment by wrhyme29** [comment]
Catacombs is still being reviewed and is not playable in the DLL. We can revisit once it has been moved into the in use DLL for testing
