### ISSUE TITLE
Swarm Eater Single Minded Pursuit Moving UI

### ISSUE THREAD

**Issue by wrhyme29** [SotMSteamMods/CauldronMods#661]
**Describe the bug**
The UI when asked whether you want to move single minded pursuit is not very helpful

**What does it affect**
Card(s): Single-Minded Pursuit, Swarm Eater Character Card
Deck(s): Swarm Eater

**To Reproduce**
1. Make a hero pursued
2. Have that hero damage a target without destroying it
3. See prompt

**Expected behavior**
At the very least, there should be an image of Single Minded Pursuit/Swarm Eater on the left so I know what effect is triggering

**Screenshots**
![20201230002704_1](https://user-images.githubusercontent.com/32969943/103334115-ddcf3b00-4a35-11eb-9464-ba3779c672ef.jpg)

**Comment by MSpekkio** [comment]
![image](https://user-images.githubusercontent.com/7707342/103375803-0e03f180-4aa9-11eb-8ea0-8da2cb2830d8.png)
