### ISSUE TITLE
v0.2.5 - Vector - Card Selection Query Indicates "Top of Deck"

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#663]
**Describe the bug**
When selecting a virus for Vector's Bioterror squad, the card should be (and likely is) shuffled into the villain deck. However, the text for the effect currently says "Select a card to put on top of the deck". This should be changed to correctly indicate a shuffle.

**What does it affect**
Card(s): Bioterror Squad
Deck(s): Vector

**Expected behavior**
Card movement text should indicate shuffling.

**Screenshots**
![20201230012752_1](https://user-images.githubusercontent.com/45407351/103336644-6f42ab00-4a3e-11eb-838b-9e12234a72ea.jpg)

**Comment by MSpekkio** [comment]
Success.

![image](https://user-images.githubusercontent.com/7707342/103373723-ae571780-4aa3-11eb-89dc-88e6620fdb9d.png)
