### ISSUE TITLE
Stranger - Glyphs

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#68]
When played with a Rune in play, the Rune deals the damage before the prompt for the Glyph to prevent the damage. Will try to test with other Glyphs as well.

**Comment by DireAvenger20** [comment]
Glyph of Decay and Glyph of Innervation both confirmed to not prevent damage.

**Comment by mgirman520** [comment]
This also occurs with Corruption.

**Comment by DireAvenger20** [comment]
As mentioned in the discord, Tango One's Chameleon Armor had a similar issue, think something is wrong with damage prevention across the board.
