### ISSUE TITLE
Echelon - Surprise Attack error

### ISSUE THREAD

**Issue by CKirkTOS** [SotMSteamMods/CauldronMods#681]
**Describe the bug**
When using a power that deals damage with two copies of Surprise Attack in play, the damage is forcibly changed to psychic.

What does it affect
Card(s): Surprise Attack
Deck(s): Echelon

**To Reproduce**

1. Have two copies of Surprise Attack in play.
2. Use a power that deals damage.

Expected behavior
The power has the option to be changed to psychic.

**Comment by LNBertolini** [comment]
This is an issue with the way the game handles multiple damage-type-changing effects; each one is supposed to list all the types it is trying to change it to, and then the players get to decide what type it ends up as. All the base-game effects either are mandatory or let you change to any damage type, so there's no way to list a damage type as "unchanged".

I can make it play better with another copy of itself, but it still won't work nicely with optional damage-type changing from another card, whether that be Guise's Yeah I'm That Guy or other mod content.
