### ISSUE TITLE
Dendron - Windcolor variant - misnamed large and small character card art

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#688]
**Describe the bug**
Both her small art atlas and large art refer to her variant character card as "OutsideTheLinesDendronCharacter." This makes the art not show up.

**Expected behavior**
Both the large art and the .json need to be corrected to call this character "WindcolorDendronCharacter" so the art displays properly.

**Comment by MSpekkio** [comment]
This is fixed in the most recent art upload.

**Comment by TopherGerkey** [comment]
The version that's currently in the downloadable .zip still has the error (I just checked) - are you talking about an upload somewhere else?
