### ISSUE TITLE
Stranger - Mark of Destruction

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#71]
Since Mark of Destruction is a hero target, it is not visible as a target unless you click "Show all targets". This is a bit of a pain, as you often want to deal it damage. Not sure if this is actually fixable. I suppose it's like Absolute Zero wanting to hit himself.

**Comment by TopherGerkey** [comment]
Necro's zombies are similar. This will primarily affect players who aren't familiar with how these decks work. It's not a bug per se, but it's awkward.

**Comment by Vilnor** [comment]
I don't see any way to change this behavior.  Similar 'friendly targets you want to damage' like Unity's Cryobot work the same way.  Marking this engine limitation and closing.
