### ISSUE TITLE
Knight's Honor power

### ISSUE THREAD

**Issue by CKirkTOS** [SotMSteamMods/CauldronMods#717]
**Describe the bug**
The Knight cannot use the power on Knight's Honor to destroy it.

**What does it affect**
Card(s): Knight's Honor
Deck(s): The Knight

**To Reproduce**
1. Play Knight's Honor
2. Click on Knight's Honor to use its power

**Expected behavior**
The Knight should be able to use the power on Knight's Honor to destroy it.

**Comment by MSpekkio** [comment]
Thank you for this report, I've confirmed this bug.

Knight's Honor in play:
![image](https://user-images.githubusercontent.com/7707342/104874750-a7445c00-5921-11eb-84ea-0179994123aa.png)


Can't Use Power from the Grant a Power UI:
![image](https://user-images.githubusercontent.com/7707342/104874693-84b24300-5921-11eb-8f82-34aab561091f.png)

Can't Use Power from regular Power phase.
![image](https://user-images.githubusercontent.com/7707342/104874734-9d225d80-5921-11eb-974a-b2c8d0f309fb.png)

**Comment by MSpekkio** [comment]
Resolution is to move the power to the Knight.

![image](https://user-images.githubusercontent.com/7707342/104875996-b082f800-5924-11eb-8d9b-8fa6c27d5e7c.png)
