### ISSUE TITLE
FSC Continuance Wanderer - Time Freeze caused softlock

### ISSUE THREAD

**Issue by origamiswami** [SotMSteamMods/CauldronMods#718]
**Describe the bug**
Time Freeze was played at the start of The Ennead's turn due to Shu's incapacitated effect. After selecting a hero for it to move next to, the game does not continue. I can enlarge the Ennead's cards, look at the villain and environment deck and trash, rewind, and exit the game, but I can't look at any hero play areas or decks and the game does not continue. It doesn't matter which hero I choose to put Time Freeze next to, it always does this. Screenshot below for what it looks like when it fails to continue.

**What does it affect**
Card(s): Time Freeze
Deck(s): FSC Continuance Wanderer

**To Reproduce**
1. Play against The Ennead in FSC Continuance Wanderer
2. Incapacitate Shu
3. Environment plays Time Freeze from Shu's start-of-turn effect

**Expected behavior**
Time Freeze should go into play next to the selected hero, then the Ennead should continue their turn

**Screenshots**
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/76876227/103495191-ed6ccc00-4e07-11eb-8691-ebb63a4aa5bb.png">

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

This issue does cause a soft lock, but I don't know how to access the logs. I've tried multiple times before, I can't figure it out on my Mac.

**Additional context**

**Comment by wrhyme29** [comment]
I did this exact situation and it did not cause a softlock - its possible that this has been resolved in a release since then. Regardless, I'm closing this issue, if you see it again, let us know.
