### ISSUE TITLE
Malichae - Ezael heal target count

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#72]
Base Ezael's heal effect only selects one target, when it should let you choose two.

EDIT: Aha, I see what's going on. Instead on select **two** targets and heal each for **one** HP, it's doing "select **one** target and heal it for **two** HP."

**Comment by Vilnor** [comment]
Thank you for the report, I'll get that fixed.

**Comment by Vilnor** [comment]
Implementation is correct, but card text in the deck list is not.
![image](https://user-images.githubusercontent.com/7707342/99740242-951e7c80-2a9c-11eb-8155-0b7b6eaa053c.png)
