### ISSUE TITLE
Starlight - Area51 variant, UI when 1 in trash and 1 in deck

### ISSUE THREAD

**Issue by qoala** [SotMSteamMods/CauldronMods#720]
**Describe the bug**
When Starlight Area 51 has 1 copy of Pillars of Creation in trash and 1 copy in deck, the UI groups both of them as the same card.

It does not seem possible to choose which one is played via the UI client, though may have been possible through the API in tests.

**What does it affect**
Card(s): Starlight (Area 51), Pillars of Creation
Deck(s): Starlight

**To Reproduce**
1. Start a game with Starlight (Area 51)
2. Have 1 copy of Pillars of Creation in deck and 1 copy of Pillars of Creation in trash (I chose to discard 1 copy from hand as part of the power)
3. Use the variant innate, Forgotten Stars.
4. See both copies grouped into the same UI entry. Choose it, for lack of an available choice.
5. See the 1 from deck played (might not be consistent)

**Expected behavior**
The player is able to choose the 1 from deck or the 1 from trash. (The "search your deck or search your trash" choice text is probably closest, even though that's not accurate because both will be searched when executing the card.)

**Screenshots**
![cauldron-20210103-starlightarea51](https://user-images.githubusercontent.com/512290/103503476-767c0700-4df8-11eb-90ac-49a241423429.jpg)

**Logs**

**Additional context**
Built at 2fe4107b51

**Comment by MSpekkio** [comment]
Thanks for the report Quola,

When the copies are both in the same location, nothing is changed.
When the two copies are in different locations, you'll now get a prompt to 'Play card in Deck' or 'Play card in Trash'.
