### ISSUE TITLE
Baccarat - ace in the hole provides no power use when used outside of turn

### ISSUE THREAD

**Issue by Savvynormal** [SotMSteamMods/CauldronMods#743]
**Describe the bug**
When Baccarat is allowed to play a card out of turn playing the card Ace in the hole will only grant an additional card play and no power uses

**What does it affect**
Card(s): Ace in the hole
Deck(s): Baccarat

**To Reproduce**
1. Use Baccarat and another deck that allows for out of turn card plays
2. Allow Baccarat to play a card out of turn
3. Play Ace in the hole

**Expected behavior**
The card should work akin to Mr. Fixer's overdrive granting two power uses out of turn.

**Screenshots**
Unable to provide a screenshot

**Logs**
Game did not freeze.

**Additional context**

**Comment by mgirman520** [comment]
![image](https://user-images.githubusercontent.com/21280903/104225229-20b8e780-5414-11eb-9203-0db6702e059b.png)
Ace in the hole states that you may use your innate power twice during **Your** power phase this turn. And as Baccarat does not have a power phase outside of his turn. He is not allowed to use it.
