### ISSUE TITLE
Titan's Flavor Text is incomplete

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#746]
**Describe the bug**
Most, if not all, of Titan's deck has incorrect flavor text - missing the speaker for each individual lines. 

**What does it affect**
Card(s): Titan's Deck
Deck(s): Titan

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by mgirman520** [comment]
Not sure why this is occurring. It looks like it' set up right.
