### ISSUE TITLE
Cricket - Chirp UI has extra Yes No UI prompt

### ISSUE THREAD

**Issue by MSpekkio** [SotMSteamMods/CauldronMods#747]
**Describe the bug**
When playing Chirp the UI doesn't allow a variable number of discards.

**What does it affect**
Card(s): Chirp
Deck(s): Cricket

**To Reproduce**
1. Have Cricket in play
2. Play Chirp with at least 3 other cards in hand

**Expected behavior**
UI should allow player to discard up to 3 cards via the Select Card or Skip dialog, and deal damage based on the number discarded.

Followup UI allows variable discard, so initial Yes no is redundant.

**Screenshots**
![image](https://user-images.githubusercontent.com/7707342/104393643-f39f2e80-5512-11eb-9fd7-4d5837ffd4af.png)

After having discarded 2:
![image](https://user-images.githubusercontent.com/7707342/104393723-20534600-5513-11eb-9a29-50bd7ac59188.png)

**Comment by LNBertolini** [comment]
It does allow variable discards, actually - if you click on the red "Stop" button just above the trash icon, you'll stop discarding cards.

**Comment by MSpekkio** [comment]
> 
> 
> It does allow variable discards, actually - if you click on the red "Stop" button just above the trash icon, you'll stop discarding cards.

I've corrected the title to reflect the problem.
