### ISSUE TITLE
Impact's Crushing Rift vs Celadroch's Pillars

### ISSUE THREAD

**Issue by jkittycat** [SotMSteamMods/CauldronMods#764]
**Describe the bug**
If Impact's Crushing Rift is used on Celadroch's Pillars, it doesn't trigger the "for every [H+1] hp this card loses..." text.

**What does it affect**
Card(s): Crushing Rift, Pillar of Storms, Pillar of Sky, Pillar of Night
Deck(s): Impact, Celadroch

**To Reproduce**
1. Play a game vs Celadroch with Impact on team
2. Hit one of the pillars at least once so Crushing Rift can be used
3. Use Crushing Rift on pillar

**Expected behavior**
The pillar's text to be activated for every threshold it passed.

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
(guessing it's a side effect of the pillar's HP being set to a value, instead of reduced? are there any other cards that could be used to test this?)

**Comment by MSpekkio** [comment]
In the game engine, SetHPAction is a specific action separate from DealDamageAction.  I've updated the pillars to recognize SetHpAction as a way to fire the reward triggers.  In the base game, the SetHpAction is used for restore effects like the Hero revives, and effects that reset Hp to max/some value.

Thank you for the report.
