### ISSUE TITLE
Necro - Undead

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#77]
Only managed to test with Zombies, but HP always showed 2 when in hand and when played, but when hit, would correctly use the hp it should have based on number of rituals in play. Example: A zombie was played with one ritual in play, it showed only having 2 hp but when dealt 2 damage, correctly was left with 1 hp left.

**Comment by TopherGerkey** [comment]
Same deal for Demonic Imps. Looks like just a display issue.

**Comment by DireAvenger20** [comment]
It seems like on later turns, the UI manages to update. Had a Ghoul out for a round without damaging it and it now shows the proper hp.
