### ISSUE TITLE
VERY minor nitpick: Hydra Tiamat typo

### ISSUE THREAD

**Issue by ChronosMysty** [SotMSteamMods/CauldronMods#776]
**Describe the bug**
The second card in Hydra Tiamat's promo says that The Mouth of the Inferno deals the highest HP "1" fire damage, but the programming and actual card promo say it does "2". 

**What does it affect**
Card(s): second rule card of Hydra Tiamat
Deck(s): Hydra Tiamat

**To Reproduce**
1. Just play a game with Hydra Tiamat and look at the second card

**Expected behavior**
It should say 2 since it clearly means 2.

**Screenshots**
![20210120200257_1](https://user-images.githubusercontent.com/77732493/105259886-afd3a700-5b5a-11eb-8024-dc3b27f4656a.jpg)

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by MSpekkio** [comment]
There are no minor typos.  Thank you.
