### ISSUE TITLE
Lady of the Wood - Thundergrey Shawl

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#79]
I believe this is not currently working as intended. Had it and Summer and play and when using the base power as fire damage, for 3 (1 + 2) damage, it was irreducible. If I understand the card correctly, this shouldn't be happening as it's above 2 damage after all modifiers.

**Comment by TopherGerkey** [comment]
I actually saw Tosx talking about this recently, I think he said that as long as the damage is below the threshold when the Shawl gets to it, it can be increased after and still be irreducible.

**Comment by DireAvenger20** [comment]
Hmm, that's a bit of a pain to keep track of. With that said, I had Summer out first, so to me under that implementation I would expect it not to trigger as I would think Summer would increase the damage first.

**Comment by wrhyme29** [comment]
Per tosx any time damage is 2 or less,  it triggers, so because the damage started below 2 and then is increased by 2, that is the expected behavior. 

Part of this has to do with the timing of irreducible damage vs modifying damage amount
