### ISSUE TITLE
Trigger.Before timing issues

### ISSUE THREAD

**Issue by breenyoung** [SotMSteamMods/CauldronMods#80]
### Description:
Triggers that rely on TriggerTiming.Before are going thru with the action before allowing the user to answer the prompt about the optional choice they have on the card

*Affected Cards Working List*
* Tango One - Critical Shot #78 
* Tango One - Chameleon Armor
* Doc Havoc - Cauterize
* Stranger - Glyph cards
________________________________________
**Deck Type:** Any decks that use TriggerTiming.Before types in their cards
**Deck:**
**Card:** See description for some examples
________________________________________
**Expected Behavior:** User should be presented with the choices *before* the action executes
**Actual Behavior:** Action is executing and user is presented the choices after the action has already taken place
________________________________________
**Steps to recreate:**
1. Play any of the cards listed in the working list in the description
1. Observe that the event that triggered the prompt is going thru and happening before the user is presented with a choice

**Comment by LNBertolini** [comment]
This is theoretically something that should be affecting Starlight's Nightlore Armor as well, but that effect works as intended - maybe compare and see if you can tell what the difference is?

https://github.com/SotMSteamMods/CauldronMods/blob/starlight/Controller/Heroes/Starlight/Cards/NightloreArmorCardController.cs

**Comment by DireAvenger20** [comment]
This also appears to be affecting Stranger's Glyphs.

**Comment by LNBertolini** [comment]
I decided to dig through the engine logs to see if that would supply any new information, and it looks like they all work on the *engine* level! Exiting and reloading the game confirms. This is purely a UI/display issue.

**Comment by breenyoung** [comment]
Doesn't seem to work without those changes.  Had Critical Shot in play and used her innate power on the turret.  Selected Yes to draw a card and it did have the Critical keyword on it.

Tango One uses the power on Tango One.
Created decision [SelectTargets/None D40 Tango One]
Created decision [SelectTarget/None D40-1 Tango One]
Created decision [YesNo/None D Tango One]
Tango One initiates 1 Projectile damage to Automated Turret.
Created decision [YesNo/None D41 Tango One]
Legacy's Galvanize increases the damage dealt by Tango One by 1.
Created decision [YesNo/None D42 Tango One]
Tango One deals Automated Turret 2 Projectile damage.
Automated Turret is now at 1 HP.
Went from Tango One's UsePower phase to DrawCard phase. 
Tango One draws Psionic Suppression.
Went from Tango One's DrawCard phase to End phase.

**Comment by breenyoung** [comment]
Here is the same action with the recompiled DLL with TriggerType.IncreaseDamage & TriggerType.WouldBeDealtDamage

Tango One initiates 1 Projectile damage to Automated Turret.
Created decision [YesNo/None D41 Tango One]
Legacy's Galvanize increases the damage dealt by Tango One by 1.
Created decision [YesNo/None D42 Tango One]
Critical Hit moved Psionic Suppression from Tango One's deck to Tango One's trash.
Tango One deals Automated Turret 5 Projectile damage.
Automated Turret is now at -2 HP.
Tango One's Snipe destroys Automated Turret!
Created decision [SelectTargets/None D43]
Created decision [SelectTarget/None D43-1]

**Comment by breenyoung** [comment]
Setting `isActionOptional` to false will keep the Yes/No dialog on screen and block the action from happening until you choose an option but the result is the same.  The log shows it working correctly but the UI doesnt reflect the log

**Comment by qoala** [comment]
This may not be useful information, but this bug effectively adds Quick Time Events to sentinels.

If you can click "yes" before all the modifiers have been added and the damage effect animation begins, the card will take effect. Requires "animate damage modifiers" option and at least one passive modifier on the damage (irreducible, +1, etc) otherwise there's no available timing window.
