### ISSUE TITLE
Leach Field prompts to Reduce Irreducible Damage

### ISSUE THREAD

**Issue by MSpekkio** [SotMSteamMods/CauldronMods#805]
**Describe the bug**
Leach Field prompts to Reduce Irreducible Damage

**What does it affect**
Card(s): Leach Field
Deck(s): Gargoyle

**To Reproduce**
Terrorize and Leach Field in play
Leach Field prompts to reduce from Terrorize damage.
Select Yes, and damage is not reduced, but Gargoyles damaged is increased

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7707342/105660875-02ce9680-5e9a-11eb-9716-e9c35a57d1ea.png)

![image](https://user-images.githubusercontent.com/7707342/105660739-b2573900-5e99-11eb-9d4f-f60c59d095a8.png)

![image](https://user-images.githubusercontent.com/7707342/105660783-cdc24400-5e99-11eb-9533-496b8626c2c8.png)

![image](https://user-images.githubusercontent.com/7707342/105660803-d7e44280-5e99-11eb-96e6-23c9a2cc30b1.png)

This may be correct, but seems odd.

**Comment by LNBertolini** [comment]
Much in the same way that irreducible damage will chew through standard Wraith's reduce-next-damage shields, you are always allowed to *try* to reduce damage even if it won't actually have an effect. This is, I am fairly sure, intentional, and actually kind of the point of the irreducibility on Terrorize.

**Comment by NinjaMonkey1234** [comment]
Does Wraith's reduce next effect still try to reduce damage, or is it just triggered because it is the next instance of damage?

**Comment by MSpekkio** [comment]
Sounds good!
