### ISSUE TITLE
Game Freeze when rewinding to Echelon's power

### ISSUE THREAD

**Issue by DireAvenger20** [SotMSteamMods/CauldronMods#809]
**Describe the bug**
Had Breakthrough in play and used Echelon's base power. Rewound because I realized I forgot to activate Leech Field for free bonus damage since Echelon's power is irreducible. After rewind, game was frozen, exiting to main menu and then continuing led to an all black screen.

**What does it affect**
Card(s): Breakthrough?, Leech Field?
Deck(s): Echelon and Gargoyle

**Screenshots**
<img width="1900" alt="black screen" src="https://user-images.githubusercontent.com/12156626/105759068-fd1a9480-5f1d-11eb-95aa-70198af844ef.png">

**Logs**
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/5869309/output_log.txt)

**Comment by DireAvenger20** [comment]
[output_log.txt](https://github.com/SotMSteamMods/CauldronMods/files/5878806/output_log.txt)
So had another softlock. Very different set up except for Gargoyle. He did have Leech Field out as well. Softlocked on a rewind again as well.

**Comment by LNBertolini** [comment]
Looking at the logs - both of these were in Vault 5, which has a known lock issue (#787 ) related to the Artifact ownership change. I think it's very likely that the Vault is responsible, rather than Leech Field.
