### ISSUE TITLE
Instruction Card Can Throw Away Relics in Vault 5

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#813]
**Describe the bug**
When playing the Sentinels in Vault 5, Moment of Sanity is giving the Sentinels Instruction card the power in addition to every other character card. 

**What does it affect**
Card(s): Moment of Sanity
Deck(s): Sentinels, Vault 5

**To Reproduce**
1. Play a game with Moment of Sanity in play and the Sentinels. 

**Expected behavior**
It's not a big problem I guess but I don't think that should be happening. 

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by wrhyme29** [comment]
This can be fixed just be adding a card.IsReal check to Moment of Sanity's  AskIfContributesPowersToCardController. Adding to my list of fixes to make.

**Comment by NinjaMonkey1234** [comment]
Might want to check Gargoyle's Mark for Execution as well. it also gives a power to all heroes and I don't think it is checking if the card IsReal.

**Comment by TopherGerkey** [comment]
Possibly related, but when Sky-Scraper is chosen to receive an Artifact, you're given a choice of all three of her character cards, including the ones not in play, to give it to.

**Comment by wrhyme29** [comment]
That one is actually a different issue where the condition is not restrictin to in play Character cards. Again will add to my list of fixes)
