### ISSUE TITLE
Tango One - Perfect Focus

### ISSUE THREAD

**Issue by ayoung1972** [SotMSteamMods/CauldronMods#82]
### Description: 
When playing Perfect Focus your prompt window which appears asks if you want to play Perfect Focus, which is the card triggering the effect vs. action being triggered which is simply "play a card" not specifically "Perfect Focus"
________________________________________
**Deck Type:** Hero
**Deck:** Tango One
**Card:** Perfect Focus
________________________________________
**Expected Behavior:** Receive a prompt if *Do you want to play a card*
**Actual Behavior:** Receive a prompt if *Do you want to play Perfect Focus*
________________________________________
**Steps to recreate:**
1.  Play perfect Focus
1. Damage Increase activates properly
1. Prompt Window appears with the following text: _Do you want to play Perfect Focus_

![perfectfocus](https://user-images.githubusercontent.com/74318975/99726503-efafdc80-2a8c-11eb-8685-a7aca33362bb.jpg)

**Comment by breenyoung** [comment]
Fixed in PR #100
