### ISSUE TITLE
Crash with Catchwater and Crane

### ISSUE THREAD

**Issue by johnnyangel360** [SotMSteamMods/CauldronMods#822]
**Describe the bug**
No target deals damage (skips right over any action that attempts to deal damage). No environment target can be destroyed without softlocking the game. Eventually hard crash of whole game.

**What does it affect**
Card(s): Crane
Deck(s): Catchwater

**To Reproduce**
Not 100% on how to reproduce, could not get log
1. Set up was against Screamachine with Omnitron, Lifeline, Gargoyle, and Starlight in Catchwater
2. Crane on Gargoyle (also had "Left Behind" on Omnitron, and the environment was pretty crowded since nothing could be destroyed, visible in screen shot)
3. Ricky G hits the crane
4. Crane becomes troubled, no longer targetable, half off the screen, not visible as attached to Ricky G or Gargoyle. Then all environment cards become problematic. Destroying any one of them leads to a soft lock. And no target can damage any other target. It doesn't attempt to do damage, any action that would do damage is just skipped. Then eventually it crashed Sentinels entirely.

**Expected behavior**

**Screenshots**
Here's a shot of the crane card on the far left
![crane](https://user-images.githubusercontent.com/77083893/106205715-ee85e480-618c-11eb-84f4-a2aed8a2d71b.jpg)

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by MSpekkio** [comment]
Thank you for the report.  I've confirmed the problem is that theCrane dealt itself damage and tried to move next to itself, and got stuck in strange land.
