### ISSUE TITLE
Lady of the Wood - Fire in the Clouds

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#83]
Using Fire in the Clouds on Swarm of Scarabs from the Tomb of Anubis resulted in a "we're working on it" message followed by the game freezing.

**Comment by wrhyme29** [comment]
Did you have Nobility of Dusk in? That behavior is consistent with that being out

**Comment by TopherGerkey** [comment]
I honestly don't remember. Will pay closer attention in the future.

**Comment by wrhyme29** [comment]
This was tied to Nobility of Dusk issue, closing
