### ISSUE TITLE
Tango One - Critical Hit

### ISSUE THREAD

**Issue by ayoung1972** [SotMSteamMods/CauldronMods#85]
### Description: 
When triggering Critical hit - it should prompt if you want to discard the top card of your deck, but it is prompting if you want to discard Critical Hit.
________________________________________
**Deck Type:** Character
**Deck:** Tango One
**Card:** Critical Hit
________________________________________
**Expected Behavior:** Prompt: _Do you want to discard the top card of your deck?_
**Actual Behavior:**  Prompt: _Do you want to discard Critical Hit?_
________________________________________
**Steps to recreate:**
1.  Have Critical Hit in play.
1. Do Damage
1. Prompt appears: _Do you want to discard Critical Hit?_
![critical hit](https://user-images.githubusercontent.com/74318975/99727658-aeb8c780-2a8e-11eb-897e-f0e8d62910c0.jpg)

**Comment by breenyoung** [comment]
Fixed in PR #100
