### ISSUE TITLE
Card Text Sweep - Echelon

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#856]
Advance and Regroup: Flavor quote is attributed to "MAGNIFICENTMARA" and "DOCHAVOC." Should be "MAGNIFICENT MARA" and "DOC HAVOC."

First Responder: Flavor quote is attributed to "Doc Havoc, Stormfront One-Shot." Should be "Doc Havoc, Stormfall One-Shot." (that one's a YIKES!)

Overwatch: Power text should read "Once per turn, when a hero target is dealt damage BY A NON-HERO TARGET, Echelon may deal..."

Staggered Assault: The second flavor quote is attributed to "MISTERFIXER." Should be "MISTER FIXER."

The Kestrel Mark II: First line of flavor text is a bit too long for the speech bubble, making it hard to read as it overlaps into the darker background.

**Comment by wrhyme29** [comment]
The overwatch one actually affects programming as well
