### ISSUE TITLE
Doc Havoc - Painkillers

### ISSUE THREAD

**Issue by breenyoung** [SotMSteamMods/CauldronMods#86]
### Description:
________________________________________
**Deck Type:** Hero
**Deck:** Doc Havoc
**Card:** Painkillers
________________________________________
**Expected Behavior:**
After it it placed under a hero at the start of their turn they should be asked if they want to deal themselves 3 toxic damage
or destroy Painkillers

**Actual Behavior:**
Hero is being prompted to select a target instead

**Actual functionality of the card works as expected** This is a cosmetic issue

________________________________________
**Steps to recreate:**
1. Play Painkillers next to a hero
1. Go to the start of that hero's turn
1. Observe the question text being asked of the hero

**Comment by Vilnor** [comment]
This issue is fixed in the next release.  Thank you for the report.
