### ISSUE TITLE
Card Text sweep: Lady of the Wood

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#860]
Rainpetal Cloak: flavor quote attribution should be "Lady of the Wood, the Wanderer's Requiem #146."

Winter: The flavor quote has an extraneous letter J floating around. It should also be broken up like so -

STARLIGHT: "It's awful quiet."
LADY OF THE WOOD: "It is the silence of an indrawn breath."
- Starcrossed #72

**Comment by mgirman520** [comment]
![image](https://user-images.githubusercontent.com/21280903/106786330-6d12d400-661c-11eb-851a-a8be37660e77.png)
Winter's quote is above. That J should be "Just wait."

**Comment by TopherGerkey** [comment]
Right, this is an instance where I was trying to match the video game rather than the physical card. When two people are talking, in the video game they get separate headings for the quotes. It's been done to all the other places where in the Cauldron, tosx did one attribution for two speakers, and this was the one (or one of the few, I'm not done yet) where it wasn't converted to match.
