### ISSUE TITLE
Card Text sweep: Quicksilver

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#864]
Guard Breaker: Flavor text attributed to THEKNIGHT, should be THE KNIGHT.

Malleable Armor: Final line of flavor text placed outside the speech bubble.

Mirror Shard: Flavor quote attributed to HALCYONSOLDIER and CPTREAGER, should be HALCYON SOLDIER and CPT. REAGER.

**Comment by mgirman520** [comment]
Fix to Malleable armor no longer matches original, but does not fall out of the bubble.
Original: 
![image](https://user-images.githubusercontent.com/21280903/106790310-5e7aeb80-6621-11eb-9ac7-1a40ce8a11b5.png)
New: 
![image](https://user-images.githubusercontent.com/21280903/106790336-69ce1700-6621-11eb-9adf-730eebb66227.png)
