### ISSUE TITLE
Card Text sweep: Tango One

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#866]
Ghost Reactor: Quotation marks need to be added around flavor quote. Attribution should be "Tango One TO Bunker," not "AND Bunker."

One Shot, One Kill: Flavor quote attribution is to CPTREAGER, should be to CPT. REAGER.

Creed of the Sniper variant: front and back large art is misnamed, currently identified as "TangoOneCreedCharacter" but should be "CreedOfTheSniperTangoOneCharacter."

**Comment by TopherGerkey** [comment]
(Note that Ghost Reactor's error is on the printed card as well, I'm just fixing the grammar.)

**Comment by mgirman520** [comment]
If the physical card is grammatically incorrect, I'm going to go with that
