### ISSUE TITLE
Doc Havoc - Gas Mask

### ISSUE THREAD

**Issue by breenyoung** [SotMSteamMods/CauldronMods#87]
### Description:
When an environment card is destroyed and Gas Mask is in play, Doc Havoc is not getting healed by 2 HP
________________________________________
**Deck Type:** Hero
**Deck:** Doc Havoc
**Card:** Gas Mask
________________________________________
**Expected Behavior:**
When an environment card is destroyed Doc Havoc should regain 2 HP if Gas Mask is in play

**Actual Behavior:**
Gas Mask does not cause Doc Havoc to gain 2 HP

________________________________________
**Steps to recreate:**
1. Play Gas Mask
1. Destroy an environment card by some means
1. Observe that Doc Havoc has not gained 2 HP due to the environment card's destruction

**Comment by Vilnor** [comment]
Thank you for the report.  I was not able to replicate this issue in the current developer branch.  Closing the issue for now.  This may be a case where the effect that removed the environment card wasn't flagged or implemented as a Destroy effect.  If you manage to replicate the problem please reopen this issue.
