### ISSUE TITLE
Card Text Sweep - Blackwood Forest

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#893]
Old Bones - Flavor text is missing quotation marks around dialogue, Should be: "This is a place of the past. Nothing stays buried," said Chrono-Ranger, watching the soil begin to move. "Not for long, anyways."

Shadow Stalker: in the flavor text "Blackwoods" should be "Blackwood's."

Shadow Weaver: More missing quotation marks around "Did that tree just move?"

Will o' the Wisp: More missing quotation marks around "They won't take you where you want to go."

**Comment by mgirman520** [comment]
Old Bones does not want quotes added to it

**Comment by mgirman520** [comment]
Shadow Stalker is fixed, the others have not
