### ISSUE TITLE
Your Darkest Secrets is Sticking Around

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#894]
**Describe the bug**
YSD won't leave play after resolving. It's just in the villain play area. 

**What does it affect**
Card(s): YSD
Deck(s): Mythos

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/74740837/106844816-6c029680-665e-11eb-87be-f95eff20290e.png)

**Logs**
https://pastebin.com/TaGV7e5P

**Additional context**

**Comment by wrhyme29** [comment]
I have not observed this behavior in any tests or in game, so I'm closing this issue. Open a new issue if this comes up again.
