### ISSUE TITLE
Doc Havoc - Search and Rescue decision-maker

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#90]
If you discard to do the reveal-and-pick-cards effect, the card selection prompt is addressed to Doc Havoc instead of the player whose deck is being revealed from. I believe this would have more effect in a multiplayer game than a single-player one.

Also, players have the option *both* to skip discarding a card *and* to decline revealing from their deck afterwards, which is technically correct, but for ease of game-flow I would suggest removing the yes-no check.

**Comment by Vilnor** [comment]
Issue is fixed, reviewed YesNo dialog, and I think it appropriate as is.  Thank you for the report and the testing.
