### ISSUE TITLE
Drift "Make Every Second Count" operating error

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#903]
**Describe the bug**
When MESC moves from position 3 to 4, it says "Choose a hero to reduce the next damage to them by 2." 

**What does it affect**
Card(s): MESC
Deck(s): Drift

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**
It should say something akin to "Choose a target to increase their next damage by 2." 

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**
It functions fine, it just reads wrong.

**Comment by mgirman520** [comment]
Duplicates #891
