### ISSUE TITLE
v0.3.1 - Malichae - Reshiel - Targetting Should Be Villain-Preferred

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#904]
**Describe the bug**
Reshiel's default targeting currently allows for all targets without modification. It should use targeting which only aims at Villain targets by default.  

**What does it affect**
Card(s): Reshiel
Deck(s): Malichae

**Screenshots**
![20210204142408_1](https://user-images.githubusercontent.com/45407351/106951801-d61a4a80-66f5-11eb-8cb1-715341b973a2.jpg)

**Comment by LNBertolini** [comment]
I've tested it out myself and it looked already is for me. Perhaps you managed to accidentally hit the "Show All Targets" button, or there's some other effect which is interacting weirdly with Reshiel? What were the circumstances, and can you replicate the effect?

**Comment by LNBertolini** [comment]
Ah, I found this - it's a problem with High Reshiel specifically.
