### ISSUE TITLE
v0.3.1 - Blackwood Forest - Vengeful Spirits - Discard Should Not Be Optional

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#911]
**Describe the bug**
Vengeful Spirits has text stating "May discard 2 Cards", and never indicates "Up to 2". This means it should only allow for discarding 0 or 2 cards. However, after discarding the first card, the second card is still optional. You should only be able to discard 0 or 2 cards. (I think the minimum action parameters may account for this, but if not, the logic should just require you to discard two cards if you choose a character rather than skipping.) 

**What does it affect**
Card(s): Vengeful Spirits
Deck(s): Blackwood Forest

**Screenshots**
![20210206001007_1](https://user-images.githubusercontent.com/45407351/107110774-461cf380-6810-11eb-8180-2a8dbb165ede.jpg)

**Comment by wac** [comment]
May also depend on the intention for this card.  
Wording on Oxygen Leak (Wagner Mars Base):  "At the start of the Environment turn, if each player discards 1 card, destroy this card".  In this case,  discard is all or nothing, and everyone must have the cards to discard to be able to do it.  This does seems like the intent for this card,  and is stricter than the option mentioned on the bug report. Reference to Fireside chat where it says everyone must do it or none.  https://sentinelswiki.com/index.php?title=Insula_Primalis/Clarifications

Wording on Challenge of Fire (Tomb of Anubis): "At the start of the Environment turn, each Player may discard up to 3 cards. If H plus 2 cards are discarded this way, destroy this card." In this case each player can discard (up to the max) but the destruction only triggers if it hits the required threshold. (Looks like how it is currently implemented).
