### ISSUE TITLE
Card Text sweep: FSC Continuance Wanderer

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#919]
Combat Cyborg: "[H] minus2" needs a space inserted between "minus" and "2."

Prehistoric Behemoth: "...deals the [H] minus 2 hero target..." should be "...deals the [H] minus 2 targets..." If this is really hitting only hero targets in the game mechanics, that's an error. 

Vortex Glitch: Flavor text is incomplete. Last sentence should be "Not all of them arrived in one piece."

Vortex Surge: Entire flavor text section needs to be inside quotation marks.

**Comment by wrhyme29** [comment]
Prehistoric Behemoth is currently only hitting hero targets, so programming will need to be changed

**Comment by kree1** [comment]
Paradox Intrusion's SpecialStringMaker is checking the trash for the keyword "vortex", not "time vortex", and therefore always says 0.
