### ISSUE TITLE
Card Text sweep: Northspar

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#922]
Frozen Solid: Missing a whole sentence, not sure if it's affecting gameplay. Should read "...either their play or power phase during their turn. INCREASE COLD DAMAGE TO THAT HERO BY 1. If that hero is dealt..."

**Comment by wrhyme29** [comment]
It is not affecting gameplay - the increase cold damage dealt to that hero is present
