### ISSUE TITLE
Card Text sweep: St Simeon's Catacombs

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#923]
Instruction card: Shows up blank in the deck browser. Uses placeholder art. We should probably do something like Chasm has for art, and revisit the blank text issue.

Dark Passenger: Flavor text needs "38" to be "38%."

Panic: "Character" is misspelled as "charcter." "At the start of that hero's turn..." should be "At the start of that hero's NEXT turn..."

**Comment by wrhyme29** [comment]
This is because it is a "CharacterCard" in the environment which the engine does not allow in the envirnoment.

The % is there, but it doesn't show because it is not included in the font.

**Comment by TopherGerkey** [comment]
If "%" is impossible, "percent" is the next best option!
