### ISSUE TITLE
Card Text sweep: Windmill City

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#926]
Cracked Water Main: Says it does Melee damage, but it should be Cold. Not sure if this is also wrong on the gameplay level.

WCPD "Chariot": Card name is using single quotation marks instead of double (Should be "Chariot.")

**Comment by wrhyme29** [comment]
This incorrect in the code as well (dealing melee damage for Cracked Water Main), so the programming will need to be changed.
