### ISSUE TITLE
High Reshiel power UI glitch

### ISSUE THREAD

**Issue by ColinAmos** [SotMSteamMods/CauldronMods#936]
**Describe the bug**
If you click on High Reshiel tucked under Reshiel to select its power, a glitchy bit of UI appears. 

**What does it affect**
Card(s): High Reshiel
Deck(s): Malichae

**To Reproduce**
1. Play a game with Malichae
2. Play Reshiel then High Reshiel
3. Get to a phase or card effect that lets Malichae use a power
3. Click on the tucked High Reshiel card

**Expected behavior**
Either the power from High Reshiel pops up as normal, or nothing happens (I'm not sure which one is intended).

**Screenshots**
![high reshiel bug](https://user-images.githubusercontent.com/35937916/107852797-b57e7e80-6de0-11eb-880e-f4f9fa0cb003.png)
![high reshiel bug - cropped](https://user-images.githubusercontent.com/35937916/107852802-b7e0d880-6de0-11eb-841e-3ae2dd535420.png)

**Logs**
n/a

**Additional context**
The power comes up properly if you click on the main Reshiel card instead.
I'm not sure if this happens with the other Djinn cards.

**Comment by LNBertolini** [comment]
This is known, and not something we can do anything about - the UI doesn't like displaying powers on cards in NextToLocations. Which is why we have High Reshiel grant the power to base Reshiel in the first place.
