### ISSUE TITLE
Thin white lines in cutscene

### ISSUE THREAD

**Issue by ColinAmos** [SotMSteamMods/CauldronMods#937]
**Describe the bug**
In the pre-game cutscene, Cauldron heroes have thin white lines that appear above their images, as well as thin white borders around their bodies.

**What does it affect**
Cutscene visuals

**To Reproduce**
1. Start a game with any number of Cauldron heroes.
2. Watch the Cauldron hero images as they slide onto the screen. It's easiest to see the horizontal lines above their images as they're moving.

**Expected behavior**
No thin white lines appear above the image nor as an outline around the characters.

**Screenshots**
![white lines bug](https://user-images.githubusercontent.com/35937916/107853508-866a0c00-6de4-11eb-9987-c595959013f6.png)
![white lines bug cropped](https://user-images.githubusercontent.com/35937916/107853510-879b3900-6de4-11eb-9015-bc8f6f9d4190.png)

**Logs**
n/a

**Additional context**
none

**Comment by wrhyme29** [comment]
This is just how it looks in the game for custom loaded art, we can't do anything about it
