### ISSUE TITLE
Tango One - status effect stacking oddly

### ISSUE THREAD

**Issue by LNBertolini** [SotMSteamMods/CauldronMods#94]
When you open up the "active status effect" screen, Tango One's damage boost effects sometimes combine and sometimes don't - playing one Perfect Focus and using Ghost Reactor's power twice ended up with her having two status effects, one for +4 and one for +3. This isn't strictly incorrect, but it did strike me as odd. 

Likely it displays one distinct status effect for each card, which would make sense given the underlying CardSource logic. This is definitely low priority, but it might be worth poking around to see if something can be done about that.

**Comment by Vilnor** [comment]
There is a CombineWithStatusEffect that might do this, but none of the existing cards directly call that method.  This is something we can defer till we have to figure out Gargoyle's mechanics.
