### ISSUE TITLE
Sabershard future power missing text

### ISSUE THREAD

**Issue by kree1** [SotMSteamMods/CauldronMods#940]
https://github.com/SotMSteamMods/CauldronMods/blob/55fea7df3c4f95180d9c4e75210025adb3bd91ad/CauldronMods/DeckLists/Hero/DriftDeckList.json#L499

This line should say "...{Drift} **deals** 1 target..."

**Comment by TopherGerkey** [comment]
Can confirm. My bad for missing this in the deck's text sweep; I can only assume this is one of the ones I did while very tired (also the current formatting for what're supposed to be "Past" and "Future" icons makes the text kind of hard to read).
