### ISSUE TITLE
Card Text sweep: Terminus

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#946]
None of Terminus' large character cards have the Abstract Tales logo added to them.

MSS Terminus and Terminus 2199 character cards have their caption colors reversed (MSS should be red, 2199 should be gray).

Railway Spike: Flavor text refers to THECONDUCTOR, should be THE CONDUCTOR. The Conductor's quote is supposed to be in  
 "<>" pointy brackets (Probably to imply it's being translated from Chinese to English, or to maybe to show the Conductor isn't really speaking aloud, or both).

Soul Ignition: Flavor text refers to THEKNIGHT, should be THE KNIGHT.

Stoke the Furnace: Flavor quote should be in pointy brackets "<>" as above.

The Chain Conductor: Flavor quote should be in pointy brackets "<>" as above.

**Comment by wrhyme29** [comment]
The < and > are not included in the font for the game (we ran into a similar problem for Drift shift symbols when brainstorming workarounds. They are in the decklist just not present in game.

**Comment by TopherGerkey** [comment]
If <> is impossible, quotation marks are the next best option, since someone is speaking.
