### ISSUE TITLE
 Industrious Hulk deals damage on its own destruction effect

### ISSUE THREAD

**Issue by Darkstand** [SotMSteamMods/CauldronMods#947]
Industrious Hulk from Oblask Crater deals damage on its own destroy effect

**What does it affect**
Card(s):  Industrious Hulk
Deck(s): Oblask Crater

**To Reproduce**
1. Play Oblask Crater
2. Play Industrious Hulk
3. Destroy Industrious Hulk
4.  Put Top Card of Deck in Hand
5.  Industrious Hulk deals hero damage

**Expected behavior**
 Industrious Hulk should not deal damage, since 'put the top card of their deck into their hand' is not a card draw
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/5991658/log.txt)

**Comment by wrhyme29** [comment]
Closed with PR #963
