### ISSUE TITLE
Infernal Choir causing deck shuffle

### ISSUE THREAD

**Issue by Darkstand** [SotMSteamMods/CauldronMods#948]
Vagrant Heart not preventing shuffling of trash into deck

Deck(s): Infernal Choir
Card(s): (Possibly) Moon Eater

**To Reproduce**
1. Play Infernal Choir
2. Flip Infernal Choir
3. Infernal Choir plays Moon Eater, Moon Eater would discard a card that is not there (deck is empty)
4. Trash is shuffled into deck

**Expected behavior**
Trash should not be shuffled back into deck"

Not sure exact cause, _probably_ not related to moon eater specifically, but may be related to a villain card causing the discard, or it being done on the villain turn.
[log.txt](https://github.com/SotMSteamMods/CauldronMods/files/5991684/log.txt)

Relevant Excerpt:
```
GameController plays Moon Eater.
Created decision [SelectNumber/None D329 Terminus]
Moon Eater moved No Rest For The Wicked from Terminus's deck to Terminus's trash.
Created decision [SelectTargets/None D330 Terminus]
Created decision [SelectTarget/None D330-1 Terminus]
Ministry Of Strategic Science Terminus initiates 3 Cold damage to Ministry Of Strategic Science Terminus.
Ace Of Sinners increases the damage dealt by Ministry Of Strategic Science Terminus by 1.
Ace Of Saints reduces the damage dealt to Ministry Of Strategic Science Terminus by Ministry Of Strategic Science Terminus by 1.
Ministry Of Strategic Science Terminus deals Ministry Of Strategic Science Terminus 3 Cold damage.
Ministry Of Strategic Science Terminus is now at 17 HP.
Created decision [SelectFunction/SelectFunction D331 Terminus]
Guilty Verdict adds 1 token to Terminus's Wrath Pool.
Created decision [SelectTarget/None D330-2 Terminus]
Created decision [SelectNumber/None D332 Gyrosaur]
Moon Eater moves 11 cards to the top of Gyrosaur's Deck.
Gyrosaur shuffles their Gyrosaur's deck.
```

(Also happened to Baccarat)

**Comment by wrhyme29** [comment]
From what I can tell, there isn't any effect on Infernal Choir or Vagrant Heart that should prevent a shuffle.

There's the following, but thats just about ignoring cards belong vagrant heart, and since vagrant heart is in the play area with cards underneath instead of in the deck, thats doesn't impact this
![image](https://user-images.githubusercontent.com/32969943/109395918-9873a080-78f4-11eb-8b3f-1d9fa4f4858e.png)

Is there another effect I'm not seeing?

**Comment by Darkstand** [comment]
![20210228213843_1](https://user-images.githubusercontent.com/77637046/109445372-6f92fe80-7a0d-11eb-8a59-84127f6f52ad.jpg)

**Comment by Darkstand** [comment]
While that does leave specific loopholes for a deck like, say, Nightmist or Omnitron that specifically shuffle trash into the deck, this was not that, When a card should be discarded from an empty deck, as happened in game, nothing should have happened.

**Comment by wrhyme29** [comment]
One more follow up on this - the way this is implemented right now, there will be a shuffle back into deck, but then it will be promptly cancelled and the cards returned, something like this:

![image](https://user-images.githubusercontent.com/32969943/109546045-4adf6b00-7a8f-11eb-8e99-7504dcd5e6ae.png)

Did this not happen? Or were there cards in deck at the end of it?

**Comment by Darkstand** [comment]
It did not. Its been awhile, but the log does not show any such line, and I seem to recall having cards in the deck at the end of it.

**Comment by wrhyme29** [comment]
Ok. Thanks for your patience with this. I will recreate your situation and see if I can get a similar result, and if I can,  I will then work on a fix.
