### ISSUE TITLE
Card Text sweep: The Infernal Choir

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#949]
Because Vagrant Heart was split into two cards, it's using placeholder art. Its large card texture needs to be duplicated and renamed "VagrantHeartPhase1" and "VagrantHeartPhase2." Similarly in Choir's atlas json, the entry for Vagrant Heart needs to be duplicated and similarly renamed.

Vagrant Heart (both): Final line of flavor text is a bit overlappy on the left side, unsure how to fix it since the quote is long.

Eclipse: LADYOFTHEWOOD should be LADY OF THE WOOD. The quotes are attributed to Department of Secrets #60, should be #100.

Moon Eater: Final line of flavor text seriously overlaps bubble edge.

**Comment by wrhyme29** [comment]
The vagrant heart and moon eater issues I don't have a fix for since the quote is so large, if i add extra line breaks, the end goes to far down and can't be seen. While in its current state, it is too far to the left, it is readable at the very least
