### ISSUE TITLE
Card Text sweep: Oblask Crater

### ISSUE THREAD

**Issue by TopherGerkey** [SotMSteamMods/CauldronMods#951]
Fresh Tracks: "If we need a monster, I suppose we know where to find one." should be in quotation marks.

Game Trail: lots of missing quotation marks. Flavor text should read: "What is wrong with this place?" said Havoc. "Everything is trying to kill everything else." Echelon chuckled. "Feels just like back home."

Gentle Transport: lots of missing quotation marks. Flavor text should read: "This is ridiculous. You can teleport," said Pyre. Vanish, clinging to the machine's neck, replied "It's nice to not be the group transportation, for once."

Impact Object Y-3A: "Such a little thing, to cause such trouble, should be in quotation marks.

Open Ground: "We don't need to hide. We just need to be faster than the other edible things." should be in quotation marks.

Unseen Terror: lots of missing quotation marks. Flavor text should read:"We tracked Swarm Eater here; I'm guessing he wants to assimilate this stuff," said Cricket. "But why's he going into the water? No robots in there..."

**Comment by wrhyme29** [comment]
The quotes all exist in the decklist, but they are for some reason not rendering, we are investigating whats going on
