### ISSUE TITLE
Drift Didn't Focus When a Turtle Shocked Her

### ISSUE THREAD

**Issue by TheRealTails** [SotMSteamMods/CauldronMods#953]
**Describe the bug**
Rapturian Shell went off and hit Drift in position 4 when she had Past Focus out - hadn't shifted this turn - but Past Focus didn't activate. 

**What does it affect**
Card(s): Rapturian Shell, Past Focus
Deck(s): Gyrosaur, Drift

**To Reproduce**
1. Gyrosaur, Mara 1929, Starlight 51, Drift, Terminus 2199 in Dungeons of Terror against Menagerie
2. Have Drift in Position 4 with Past Focus out, and not shifted yet this turn, have Gyrosaur have Rapturian Shell with no crash cards in hand. 
3. Have Gyrosaur hit Drift with Rapturian Shell's End of Turn effect.
4. Past Focus didn't activate.

**Expected behavior**
Past Focus to activate. 

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

**Comment by wrhyme29** [comment]
Closed by #961
