### ISSUE TITLE
Violent Assist fails to prevent damage modified by Enhanced Senses

### ISSUE THREAD

**Issue by kree1** [SotMSteamMods/CauldronMods#954]
**Describe the bug**
When I used Telescoping Staff to have Cricket hit Gargoyle for Violent Assist, I got the VA prompt to prevent the damage and said Yes, and got the damage boost... but when Anathema's Enhanced Senses changed the damage type to sonic, it caused Cricket to also deal the damage.

**What does it affect**
Card(s): Violent Assist, Enhanced Senses

**To Reproduce**
1. Fight Anathema. (I used Accelerated Evolution Anathema and Dragon Ranger Gargoyle, but I don't know if that matters.)
2. Wait for him to play Enhanced Senses so all damage is Sonic.
3. Get Gargoyle's Violent Assist out so he can eat damage from other heroes.
4. Have another hero initiate >0 damage to Gargoyle.
5. When Violent Assist prompts you to prevent the damage, choose Yes. Gargoyle will get the damage boost...
6. ... and then Gargoyle will get hit.

**Expected behavior**
When you choose Yes for Violent Assist, it prevents the damage that would be dealt to Gargoyle, and boosts Gargoyle's next damage by the amount of damage that was prevented.

**Logs**
https://pastebin.com/cqZMQHTP
Line 331

**Comment by wrhyme29** [comment]
I built this situation in both the test suite and in game UI and I was unable to replicate this bug in either. Closing this issue, if you see it again please let us know.
