### ISSUE TITLE
v0.4.0 - Starlight/The Knight - Nightlore Council/Wasteland Ronin - Multi-Character Phase Logic Fails when All Characters are Removed From Game - EDIT: CLOSE, NOT AN ISSUE

### ISSUE THREAD

**Issue by Ruduen** [SotMSteamMods/CauldronMods#965]
EDIT: This can be closed - apparently a fireside chat indicates this is working as expected. 

**Describe the bug**
When all of the relevant Hero Characters for a multi-character Hero are removed from the game, the GoToPhase logic fails and begins skipping from the Start Phase right to the End Phase, not allowing for any Incapacitated Powers. 

I primarily reproduced this in regression tests, using the following test for Nightlore Council. Note that I have also tested with Wasteland Ronin and confirmed the same issue. 

**What does it affect**
Card(s): Nightlore Council Variant/Wasteland Ronin Variant
Deck(s): Starlight/The Knight

**To Reproduce**
Here is the code used in order to reproduce this. Note that the incapacitation checks work fine - it is just the Phase Logic afterwords that fail. 

```
        [Test()]
        public void TestNightloreCouncilIncapsRemovedFromGame()
        {
            var nightloreDict = new Dictionary<string, string> { };
            nightloreDict["Cauldron.Starlight"] = "NightloreCouncilStarlightCharacter";
            SetupGameController(new List<string> { "BaronBlade", "Cauldron.Starlight", "Legacy", "TheSentinels", "TheFinalWasteland" }, false, nightloreDict);

            StartGame();
            Card card = PlayCard("UnforgivingWasteland");

            foreach (Card charCard in EachStarlight)
            {
                AssertNotIncapacitatedOrOutOfGame(starlight);
                DealDamage(card, charCard, 40, DamageType.Melee);
            }

            AssertIncapacitated(starlight);
            GoToUseIncapacitatedAbilityPhase(starlight);
        }
```

**Expected behavior**
Incapacitation phases should work as expected.

**Comment by wrhyme29** [comment]
Closing, working as expected in engine
